.github/workflows/ci.yml
.golangci.yml
.vscode/settings.json
cmd/astro-wasm/astro-wasm.go
go.mod
go.sum
internal/escape.go
internal/parser.go
internal/printer/print-to-js.go
internal/token.go
internal/token_test.go

You can run this test with:
```
go test -v ./internal
```
It should pass

Add tokenizer test

---

internal/printer/printer_test.go
internal/token.go
internal/token_test.go

OK I lied; I actually did poke at it a little more when I said I wasn’t gonna. So adding the example from our `examples/framework-react` code, it actually does hang in the parser so I guess that makes more sense now!

Framework react test

---

internal/printer/printer_test.go
internal/token.go

Updates tests to get CI passing again

Get tests passing

---

internal/printer/printer_test.go
internal/transform/transform.go

Fixes a bug where we are trying to extract `<script>` tags with no body content.

Fix empty <script> tags

---

internal/parser.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/scope-html.go

- Components now accept slots
- `<* slot="">` must be the child of a Component

Add support for slotted content

---

internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/token_test.go

Fixes a bug with conditional rendering.

Bugfix: conditional rendering

---

internal/print-to-source.go
internal/transform/scope-css.go
internal/transform/scope-html_test.go
internal/transform/transform.go
internal/transform/transform_test.go

When encountering a `<style global>` element, we'll handle it properly and won't scope any elements in the same file.
Closes https://github.com/snowpackjs/astro/issues/1295

Add support for Global styles

---

internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/printer/utils.go
internal/transform/scope-css.go
internal/transform/transform.go
internal/transform/utils.go

I'll walk through this changes in a review!

Add support for scripts, `<script hoist>`

---

internal/printer/print-to-js.go
internal/printer/printer_test.go

Adds support for:
```astro
<div slot={name}>contents</div>
```

Allow slot names to be expressions

---

.changeset/config.json
.github/workflows/release.yml

- set access to "public" as [recommended](https://github.com/atlassian/changesets/blob/main/docs/config-file-options.md#access-restricted--public) by the docs
- run `git push --follow-tags` as [recommended](https://github.com/atlassian/changesets/blob/main/docs/command-line-options.md#git-tags) by the docs

Fix Release Script

---

.changeset/selfish-humans-crash.md

Add changeset for #58

---

.github/workflows/ci.yml
.github/workflows/release.yml
cmd/astro-wasm/astro-wasm.go
lib/compiler/test.js
package.json

Tests the version of the compiler built automatically by CI
Tests should pass (🤞)

Add WASM test

---

.changeset/funny-adults-promise.md
internal/node.go
internal/parser.go
internal/printer/printer_test.go

- Reported on Discord. Compiler would panic if everything was components because we were trying to pop a non-existent stack
Test added from exact repro
Bug fix only

fix: do not panic if all components

---

.changeset/polite-ties-destroy.md
internal/parser.go
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Closes https://github.com/snowpackjs/astro/issues/1807
- Fixes expressions inside of `select`
Added two tests for common use cases.
Bug fix

fix: expressions inside of <select>

---

internal/printer/printer.go

- Do it the hard way
- This fixes the OSX `\x00` issues. I don't know why. I just know that it does.
Fixes tests in /astro
N/A

Change how imports are printed

---

.changeset/seven-eagles-sell.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- https://github.com/withastro/astro-compiler/pull/163 introduced an extra `)` character in the output, throwing https://github.com/withastro/astro/pull/1995
- Removed it.
Tests updated
Bug fix only

fix: syntax error in output

---

.changeset/lucky-insects-work.md
internal/transform/transform.go
internal/transform/transform_test.go

- My logic for checking if something was an only sibling was... bad.
- Now it is better.
Existing tests passing, new test added!
Bug fix

fix: component only failure

---

.changeset/bright-goats-fail.md
internal/printer/printer_test.go
internal/transform/scope-css.go

Fixes https://github.com/withastro/astro/issues/1992. Simple fix.
Test added.
Bug fix only

Fix CSS comments

---

CONTRIBUTING.md

Add note on tinygo downgrading

---

.github/workflows/ci.yml
.github/workflows/release.yml

- Updates GitHub Actions to leverage improvements made to actions in main `astro` monorepo.
We'll see!
QoL improvement only

Improve GitHub Actions

---

.changeset/cyan-cameras-punch.md
.changeset/polite-planes-shake.md
.github/workflows/ci.yml
.github/workflows/release.yml
Makefile
internal/parser.go
internal/printer/printer_test.go
internal/token.go
lib/compiler/CHANGELOG.md
lib/compiler/package.json
lib/compiler/test/body-expression.test.mjs
lib/compiler/test/test.mjs
lib/compiler/test/top-level-expression.test.mjs

- This should finally unblock https://github.com/withastro/astro/pull/2057, verified locally
- There was one final edge case the new fragment behavior wasn't catching with expressions
Tested locally in this repo, linked in `astro` repo
Bug fix only

Final expression fix

---

.changeset/orange-yaks-thank.md
internal/parser.go
internal/printer/printer_test.go

Fixes https://github.com/withastro/astro/issues/2069
Tests added
No docs needed

Fix sibling expressions within table context

---

.github/ISSUE_TEMPLATE/---01-bug-report.yml
.github/ISSUE_TEMPLATE/config.yml

chore: add issue template

---

.changeset/fuzzy-books-give.md
internal/parser.go
internal/printer/printer_test.go

- Closes https://github.com/withastro/astro/issues/2104
- Fixes regression with active formatting elements when Components follow expressions.
Test added, as well as an additional regression test
Bug fix only

fix: regression with active formatting elements

---

.changeset/chatty-chefs-swim.md
LICENSE
lib/compiler/package.json

- Closes https://github.com/withastro/compiler/issues/216
N/A
N/A

Add License

---

.changeset/fair-shirts-look.md
internal/parser.go
internal/printer/printer_test.go

- Closes https://github.com/withastro/compiler/issues/212
Closes https://github.com/withastro/compiler/issues/214
- Fixes how expressions are handled inside of active formatting elements
- Minimal tests added for open issues
N/A, bugfix only

fix(#212, #214): improve expressions inside of active formatting elements

---

internal/token.go
internal/token_test.go

- Attempting to debug a potential issue for https://github.com/withastro/astro/issues/2296, but these tests are helpful to have anyway!
Just tests
Just tests

Add more attribute tokenizer tests

---

cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
lib/compiler/shared/types.ts

This reverts commit 502f8b8cf13ce775cd196ee3b9e37003f6c3c053.
I believe this is causing astro to fail on Windows but have not tracked down why.

Revert "Add hoisted scripts to TransformResult (#247)"

---

.changeset/tiny-geese-peel.md

Adds a changeset for the revert.

Add a changeset for the revert

---

.changeset/gentle-tips-lick.md
.changeset/twenty-starfishes-matter.md
cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
lib/compiler/shared/types.ts

- Astro had to rollback 0.8.1 due to a bug with the compiler. 
- It turned out to be the use the `dedent` package. See passing tests here: https://github.com/withastro/astro/pull/2421

Fix usage in astro

---

.changeset/bright-pets-reply.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go

- If using `<style define:vars>`, those get added to the STYLES array.
Added tests for styles and scripts when using StaticExtraction flag.
Bug fix only

Support define:vars with static extraction

---

.changeset/stupid-glasses-sleep.md
lib/compiler/browser/utils.ts
lib/compiler/node/utils.ts
lib/compiler/test/parse/serialize.ts

- Adds a `serialize` util to `@astrojs/compiler/utils`
- Will unblock the Prettier plugin
Test added
No

Add serialize util

---

.changeset/poor-shrimps-applaud.md
packages/compiler/browser/utils.ts
packages/compiler/node/utils.ts
packages/compiler/test/parse/serialize.ts

- Added an option for self-close that defaults to true.
Added tests

[AST] Add `self-close` option to serialize util

---

internal/js_scanner/js_scanner.go
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Removes our `HasExports()` scanning since it was over-eager
- No longer panics
- Test added
Bug fix only

fix(#319): remove export panic

---

internal/printer/printer_test.go

- Small change to add `is:inline` to a test
This is that
Bug fix only

Fix failing test

---

.changeset/fifty-lizards-joke.md
internal/token.go
internal/token_test.go

- Closes https://github.com/withastro/compiler/issues/348
Tokenizer test added
bug fix only

Move `openBraceIsExpressionStart` assignment before `<>` check

---

.changeset/violet-moose-compete.md
internal/parser.go
internal/printer/printer_test.go

- Fixes https://github.com/withastro/compiler/issues/367
Test added
Bug fix only

fix(#367): expressions inside caption, colgroup

---

.changeset/light-days-poke.md
internal/parser.go
internal/printer/printer_test.go
packages/compiler/test/parse/orphan-slot.ts

- Fixes https://github.com/withastro/compiler/issues/365
- Fixes https://github.com/withastro/compiler/issues/361
Test added
Bug fix only

Fix orphan slot panic

---

internal/js_scanner/js_scanner_test.go
internal/printer/printer_css_test.go
internal/printer/printer_test.go
internal/token_test.go
internal/transform/scope-css_test.go
internal/transform/scope-html_test.go
internal/transform/transform_test.go

chore(lint): fix lint simple

---

.changeset/angry-poems-promise.md
internal/parser.go
internal/printer/printer_test.go

- Fixes #368, various edge cases with table expressions
Test added
Bug fix only

fix(#368): fix edge cases with expressions inside of tables

---

internal/parser.go

Fixes test failure that wasn't being caught
This is the test
Bug fix only

fix: orphan slot bug

---

cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/printer/print-to-tsx.go
internal/printer/printer.go
internal/printer/utils.go
packages/compiler/node/index.ts
packages/compiler/shared/types.ts
packages/compiler/test/tsx/basic.ts
packages/compiler/test/tsx/raw.ts
packages/compiler/test/tsx/script.ts

- Add `convertToTSX` method to emit pure TSX that we can typecheck
- cc @Princesseuh 
Simple test added, need more edge cases covered!
TODO

Add TSX output

---

.changeset/rare-rivers-sit.md
internal/parser.go
internal/printer/printer_test.go
internal/token_test.go

- Fixes #418
- Components with only text are now properly printed only once
Test added
Bug fix only

Fix duplicate text

---

.changeset/cyan-readers-divide.md
.github/workflows/release.yml

- The JS was not being built during the release.

Build JS when doing the release

---

.changeset/pretty-horses-cough.md
internal/parser.go
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Closes #441
- Fixes edge case with fallback content inside of slots
- Edge case was hit when `slot` was a top-level child
Tests added
Bug fix only

Fix fallback content in slots

---

internal/printer/printer_test.go

- Follow-up to https://github.com/withastro/astro.build/pull/187
This is that
N/A

Add `map` regression test

---

.changeset/angry-knives-sip.md
internal/parser.go
internal/printer/printer_test.go

- Fixes #431
- Fixes #428
- Fixes #427 
- Fixes #417 
- Fixes #384 
- Fixes #381
- Fixes #374
Many tests added

Table fixes

---

.gitignore
lerna.json
package.json
pnpm-lock.yaml

Remove Lerna, in favor of integrating everything into PNPM.
Signed-off-by: Randall <ran.dall@icloud.com>

Remove Lerna

---

.changeset/proud-drinks-fail.md
internal/token.go
internal/token_test.go

- Fixes https://github.com/withastro/astro/issues/3793
- Better handling for TS generics inside of expressions
Test added
Bug fix only

Better handling for TS generics

---

.changeset/stale-starfishes-fry.md
internal/transform/transform.go
packages/compiler/test/client-directive/special-characters.ts

- Companion PR to https://github.com/withastro/astro/pull/4263
- We weren't handling non-URL safe characters when matching imports. Now we are!
Added!
Bug fix only

Better handling for special characters

---

.changeset/kernkraft-400.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/printer/utils.go

Fixes: #471
Special Thanks to @aFuzzyBear @okikio for their continued support and efforts.
Signed-off-by: Randall <ran.dall@icloud.com>

Fix quotations in pre-quoted attributes

---

.changeset/tricky-mugs-wash.md
internal/printer/print-to-js.go

This reverts commit af28cc7347e8ee21c3724aee0673e2268af8dd59.
Temporary, bug was found

Revert "Make Astro styles being printed after user imports (#520)"

---

.changeset/olive-forks-glow.md
internal/js_scanner/js_scanner.go
packages/compiler/test/basic/export.ts

- Closes #517 
- Fixes edge case with TypeScript transformations
Test added
N/A

Fix TypeScript newline

---

.changeset/shy-lemons-wonder.md
internal/node.go
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/transform/transform.go

- Fixes https://github.com/withastro/astro/issues/4770
- If there is only a `<script>` and nothing else, we need to do head injection.
- Printer test added
N/A, bug fix

Ensure that head injection occurs if there is only a hoisted script

---

.changeset/i-predict-a-riot.md
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/README.md
.devcontainer/library-scripts/common-debian.sh
.devcontainer/library-scripts/go-debian.sh
.devcontainer/library-scripts/meta.env
.devcontainer/library-scripts/node-debian.sh
.devcontainer/library-scripts/node-volta-debian.sh
.vscode/settings.json
packages/compiler/README.md

This adds the configuration for VSCode `Devcontainer` and Codespaces.

Add `devcontainer` configuration

---

.changeset/plenty-points-cheat.md
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go

Fixes #556
_Side note:_ I'm participating in Hacktoberfest, so I would like this PR to be labed as `hacktoberfest-accepted` 😄

fixed regression caused by #546

---

.changeset/tough-bananas-bathe.md
internal/printer/print-to-tsx.go
internal/printer/printer.go
internal/token.go
packages/compiler/test/tsx-errors/unfinished-component.ts
packages/compiler/test/tsx-sourcemaps/attributes.ts
packages/compiler/test/tsx/basic.ts

Fixes issues outlined in https://github.com/withastro/compiler/issues/563.
This isn't everything, but it's definitely NWTWWHB!
- Windows issue is confirmed, will need to follow-up with a fix
Wasm tests added
Bug fixes only

Fix TSX Issues

---

.changeset/cold-vans-happen.md
internal/parser_test.go
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts
packages/compiler/test/tsx/props.ts

- Closes #571
- Fixes a logic bug in the end tag sourcemap handling. 
- Adds closing location tests to the Go codebase, all passing
Bug fix only

Improve end tag sourcemaps

---

.changeset/thin-wasps-promise.md
internal/parser.go
internal/printer/printer_test.go
packages/compiler/test/parse/orphan-head.ts

- Fixes #585
- Follow-up to https://github.com/withastro/compiler/pull/541 which did not fix the issue entirely
Tests added
Bug fix only

Fix style tag moving inside `html`

---

.changeset/little-kings-fly.md
internal/printer/printer.go

- #601 introduced a regression on Windows
- This fixes it
Have to release it to find out! 😓 
N/A, bug fix

fix(tsx): windows sourcemap bug

---

.changeset/brave-rivers-complain.md
internal/printer/print-to-tsx.go
internal/sourcemap/sourcemap.go

- Fix windows sourcemaps (again again)
We'll do it live
Bug fix only

Windows sourcemaps (take 3)

---

.changeset/gentle-shrimps-end.md
internal/printer/print-to-tsx.go
internal/sourcemap/sourcemap.go

- Fixes Windows sourcemaps (hopefully)
- Reverts some previous changes
Have to release to test
Bug fix

Windows sourcemaps (take 4)

---

.changeset/calm-terms-jump.md
internal/printer/printer.go
packages/compiler/test/tsx-sourcemaps/template-windows.ts

- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.

fix(tsx): print `\r` in output

---

packages/compiler/test/tsx-sourcemaps/deprecated.ts
packages/compiler/test/tsx-sourcemaps/error.ts
packages/compiler/test/tsx-sourcemaps/hover.ts
packages/compiler/test/tsx-sourcemaps/module.ts

- These are minimal test cases that are failing in the Language Tools repo
This is that
N/A

Add Windows tests

---

.changeset/clever-ligers-fail.md
internal/parser.go
packages/compiler/test/basic/expression-then-node.ts

- Fixes issues in https://github.com/withastro/astro/pull/5369
Test added
Bug fix only

fix: properly handle expression literals

---

.changeset/popular-wombats-nail.md
internal/js_scanner/js_scanner.go
internal/printer/print-to-tsx.go
internal/printer/utils.go
packages/compiler/test/tsx-sourcemaps/404.ts
packages/compiler/test/tsx-sourcemaps/attributes.ts
packages/compiler/test/tsx-sourcemaps/complex-generics.ts

- Closes #631
- Addresses all found feedback in issue
- Improves test coverage
Mostly tests ☺️
N/A, bug fixes only

Better TSX coverage and fix some compiler issues

---

.changeset/spicy-beans-train.md
internal/parser.go
packages/compiler/package.json
packages/compiler/test/table/components.ts
packages/compiler/test/table/expressions.ts
packages/compiler/test/table/in-expression.ts
pnpm-lock.yaml

- Closes #626, closes #572, closes #550, closes #538, closes #509
- Uses `inLiteralIM` for more table / expression conditions, which matches user expectations that what they write is what they get
Added test case for every linked issue. Tests for panic, tests that generated JS is well formed. Where possible, tests that markup is correctly nested.
Bug fix only

Table bugs revisited

---

.changeset/light-berries-laugh.md
internal/printer/print-to-json.go
packages/compiler/sourcemap.astro.js
packages/compiler/test/parse/position.ts

- Fixes a bug where self-closing tags were off-by-one in the AST
Tests added
N/A

Account for self-closing tag position

---

.github/workflows/snapshot-release.yml

- Update the snapshot release to build both the wasm and js.

Build all packages in the snapshot release

---

.changeset/yellow-needles-occur.md
internal/js_scanner/js_scanner.go
packages/compiler/test/tsx/non-latin.ts
packages/compiler/test/tsx/props-and-staticPaths.ts
packages/compiler/test/tsx/props.ts

- Fixes edge case where Props generic detection was getting tripped up.
- Runs a few tests that I'm not sure were running previously
Adds a new test
Bug fix only

Fix combo of props and getStaticPaths

---

internal/transform/transform_test.go

- Adds `FuzzTransformScoping`
Another fuzz test, can be run via `go test ./internal/transform -fuzz=FuzzTransformScoping`
Ends up testing nearly the same code :shrug:

Add `internal/transform/transform_test.go#FuzzTransformScoping`

---

.changeset/clean-spiders-perform.md
.github/workflows/ci.yml
internal/js_scanner/js_scanner.go
internal/printer/print-to-js.go
internal/printer/print-to-json.go
internal/printer/print-to-tsx.go
internal/token.go
internal/transform/transform.go
internal/transform/utils.go
packages/compiler/CHANGELOG.md
packages/compiler/browser/utils.ts
packages/compiler/node/utils.ts
packages/compiler/test/tsx-sourcemaps/complex-generics.ts
packages/compiler/test/tsx-sourcemaps/unfinished-literal.ts

- Fixes some typos in code and comments, I'm not sure this will pass immediately 😅

Fix all the typos :D

---

.changeset/gentle-queens-allow.md
internal/js_scanner/js_scanner.go
packages/compiler/test/basic/export.ts

- Closes https://github.com/withastro/astro/issues/5818
- Adds better handling when exporting types
- Specifically, we might hit EOF when iterating over tokens when something isn't closed. If we do, we'll just hoist everything out.
Test added and existing tests passing
Bug fix only

Fix `export type` hang

---

internal/token.go
packages/compiler/test/basic/lt-gt-text.ts

- Found a test that had a logic error and it turns out was actually failing!
- Fixed the underlying bug
- Test passes now
This is that.
Bug fix only

Fix accidentally failing test

---

.changeset/thick-jeans-wash.md

Ceremonial release of 1.0.0
No changes
No changes

Release 1.0.0

---

.changeset/early-trees-rush.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts

The fateful day came where writing an actual solution for this instead of doing some clumsy search was the better solution. Hopefully that covers everything now!
Added a test!
N/A

Better handling for invalid attributes in TSX

---

.golangci.yml

Update CI lint settings
N/A
N/A

Fix lint error

---

.changeset/grumpy-clocks-jump.md
internal/printer/printer.go
internal/printer/printer_test.go

Closes https://github.com/withastro/astro/issues/6316
Updates namespaced attribute logic to ensure `namespace:` prefix is always included
Regression test added, all existing tests pass
N/A, bug fix

Preserve namespaced attributes when using expressions

---

.changeset/rare-rocks-relate.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

Fix https://github.com/withastro/compiler/issues/739
Added a tokenizer and a printer test
bug fix only

Improve handling of self-closing tags returned from expression

---

.changeset/five-kangaroos-march.md
packages/compiler/browser/index.ts

What the title says
Tested manually
N/A

Expose `convertToTSX` function in compiler browser bundle

---

.changeset/rotten-elephants-refuse.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts

Fix https://github.com/withastro/compiler/issues/782
Added a test
N/A

Fix usage of fragments in TSX

---

.changeset/empty-donuts-grin.md

I forgot the changelog when I implemented https://github.com/withastro/compiler/pull/842

Changelog for feature 

---

.github/workflows/issue-labeled.yml
.github/workflows/issue-opened.yml

- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.

ci: Add auto-labelling like the main repo has for issues

---

.github/workflows/lint-changeset.yml

Just scaffolding for this action

Add changeset lint action

---

internal/printer/printer_test.go

Add a regression test, closes #850. Issue was originally fixed in #897.
Changeset not needed as this PR only adds a test
Added a printer test to ensure a correct output
N/A bug fix

Add regression test for #850

---

internal/printer/printer_test.go

#353 was seemingly fixed in #897. I added a regression test just in case.
N/A bug fix

Add regression test for #353

---

internal/printer/printer_test.go

- Closes https://github.com/withastro/compiler/issues/713 which seems to have been fixed in 2.4.0!
Added a regression test to close the issue
N/A bug fix

Add regression test for #713

---

.git-blame-ignore-revs

- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.

chore: ignore format commit in git blame

---

.changeset/small-lions-reflect.md
internal/printer/__printer_js__/Component_with_await.snap
internal/printer/__printer_js__/Fragment_shorthand_with_await.snap
internal/printer/__printer_js__/Fragment_with_await.snap
internal/printer/__printer_js__/Fragment_wrapping_link_with_awaited_href.snap
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go

- Move adding async prefix to printer method
- Fixes https://github.com/withastro/astro/issues/13334
Printing following payload:
```
<body><Fragment> { await Promise.resolve("Awaited") } </Fragment></body>
```
bug fix

fix: await issue with fragment
