withastro/compiler

internal/printer/printer_test.go
internal/token.go
internal/transform/scope-css.go
internal/transform/scope-css_test.go

Porting this test into the Go compiler: https://github.com/snowpackjs/astro/blob/main/packages/astro/test/astro-scoped-styles.test.js.
This adds support for `:global()` as well as some trickier CSS queries that can easily be messed up.
✅ All tests added are passing (`scope-css_test.go`), but it should be noted that the `main` branch isn’t passing yet so CI will still fail overall.

Add scoped CSS feature & tests

---

internal/printer/print-to-js.go
internal/printer/printer_test.go

Previously `<Component></Component>` would not render a fallback because `` was passed in as a slotted node.
We lose a little fidelity here, but I can't think of a good way to preserve comments when passing them to various `<slot>` elements.

Do not insert `CommentNode` into slots

---

internal/transform/scope-html.go
internal/transform/scope-html_test.go

This fixes https://github.com/snowpackjs/astro-repl/issues/10 and a few other edge cases. Handles as many scoped class attribute situations as possible.
Unhandled, and unclear _how_ to handle: `{...value}` that contains `class`.

Fix dynamic classes

---

internal/parser.go
internal/printer/printer_test.go
internal/token_test.go

Previously, an `EndExpressionToken` in the `textIM` would revert the parser to its' original InsertionMode. Turns out, that's the wrong thing to do! If we're in `textIM`, anything after the expression should remain in the `textIM`. The InsertionMode will be reset automatically.
Closes https://github.com/snowpackjs/astro/issues/1362

Fix text following expression

---

internal/printer/print-to-js.go

Our `slot` tests were flaky because they relied on unstable output. This fixes the `slot` output so that it is always alphabetical.
This shouldn't have an effect on userland code because slots are explicitly placed by the user. They never access this object directly. This just fixes our test suite.

Sort slot keys for stable output

---

.changeset/brown-windows-fold.md
internal/parser.go
internal/printer/printer_test.go

This fixes https://github.com/snowpackjs/astro/issues/1493
You can do stuff like:
```astro
{cond && <span></span>}
```
At the top-level now.

Allow top-level conditional expressions

---

internal/parser.go
internal/printer/printer_test.go

- Fixes this sort of thing: `{image && (<meta property="og:image" content={new URL(image, canonicalURL)}>)}`
- Previously we were parsing head elements using textIM (oops).
Test added
N/A

Fix expression parsing when HTML is wrapped in parens

---

.changeset/chilled-socks-buy.md
internal/transform/scope-css.go
internal/transform/scope-css_test.go

Updates the scoped CSS transform to support CSS variables.  Currently, the colon is lost during the transform and `--bg: red` is output as `--bg red`
Added a test to make cover CSS variable parsing
bug fix only

fixing parsing for CSS variables in style parsing

---

.changeset/brown-mirrors-grin.md
internal/js_scanner/js_scanner_test.go
internal/parser.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/test_utils/test_utils.go
internal/token.go
internal/token_test.go

- Fixes `Fragment` and `<>` handling for backwards compat
- Panics when encountering `< attr=...>` and guides users to replace with `<Fragment attr=...>`.
Panic tests added to tokenizer test suite, refactored `AnsiDiff` into `test_utils` module
N/A, matches Astro Classic™ behavior.

Fix: `<Fragment>` and `<>`

---

.changeset/beige-adults-wait.md
internal/node.go
internal/parser.go
internal/printer/printer_test.go
internal/token_test.go
internal/transform/transform.go

- Previously, scripts/styles that were siblings of each other appeared to only be processed up until the first script or style tag.  
- I assumed this was a tokenization or parser bug, but it was in our `transform` module!
- Previously, we would add a style to `doc.Styles` and immediately remove it from it's parent node. Doing this _during_ the recursive `walk` function corrupted the children, meaning following nodes would be left in place.
- The fix was to **not remove** hoisted `style` or `script` elements until **after** the `doc` was `walk`ed.
Added a test
Bug fix only

fix: script/style sibling issue

---

.changeset/quiet-dolphins-beam.md
internal/printer/printer_test.go
internal/transform/transform.go

- Followup to https://github.com/snowpackjs/astro/pull/1721. 
- Rather than reverse the final order from the `astro` side, the correct fix is to reverse the order per-file in the compiler.
**Previously,** text was _red_.
**With this change,** text is _yellow_.
Tests updated, but not testing this specifically
Bug fix only

Fix: `style` ordering

---

.changeset/khaki-mails-remain.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

Fixes https://github.com/snowpackjs/astro/issues/1717.
Previously, we would compile all slots to use our custom Astro slot handling. For `custom-elements`, `slot` has different semantics and should be left up to the custom element itself.
This change passes through any slotted elements as written. 
Test added
Bug fix only

Preserve slots inside `<custom-element>`

---

.changeset/wet-crews-sin.md
internal/token.go
internal/token_test.go

- Followup to #122, which was an incomplete solution.
- This fixes handling of `'`, `"`, `` ` ``, and `/` character inside of elements that are inside of expressions.
- Closes https://github.com/snowpackjs/astro/issues/1478
Tests added
Bugfix only

fix: better handling for text inside of elements inside of expressions

---

.changeset/tiny-ties-crash.md
internal/printer/printer.go
internal/printer/printer_test.go

- We had a bug in our `printAttribute` function that would print namespaced attributes in an invalid way. 
- This is fixed, unblocking attributes like `xmlnm:xlink`
Test added
Bug fix only

Fix namespaced attribute printing

---

.changeset/forty-crews-greet.md
internal/js_scanner/js_scanner.go
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Fixes `getStaticPaths` behavior, because it allows `getStaticPaths` anywhere in the file. The function is hoisted to the top of the file.
Tests added
N/A Backwards compat

Implement `getStaticPaths` hoisting

---

internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go

See https://github.com/snowpackjs/astro/pull/1743
- When a component only included `<script hoist>`, we would print malformed JS because the `doc` was empty when we tried to print it.
- Now, if we hoist out all the contents, we inject an empty `FrontmatterNode` with an empty `TextNode` child.
- This allows the `printToJs` function to keep doing it's thing and returns valid JS.
This is not tested because it is a difficult edge case to test for with our current setup
Bug fix

fix: script hoist behavior

---

.changeset/nervous-cycles-remain.md
internal/printer/printer.go
internal/printer/printer_test.go

- Adds `$$metadata.resolvePath()` to `client:only` components.
- Needed to unblock https://github.com/snowpackjs/astro/pull/1716
Tests updated
N/A, internal implementation

feat: use `$$metadata.resolvePath` to support `client:only` directive

---

.changeset/tidy-zoos-sin.md
internal/js_scanner/js_scanner.go
internal/printer/printer_test.go

Given the following input:
```
---
export async function getStaticPaths() {
const data = await fetch(`${import.meta.env.PUBLIC_API_URL}/api/posts`)
.then((res) => res.json())
.then(() => {
console.log('data received')
});
}
---
```
This is what it’d generate:
```diff
+ import * as $$module1 from 'data received';
export async function getStaticPaths() {
const data = await fetch(`${import.meta.env.PUBLIC_API_URL}/api/posts`)
.then((res) => res.json())
.then(() => {
console.log('data received')
});
}
```
Basically, `import.meta.env` would be accidentally hoisted up as an import. As to why the `console.log` got the import I’m just guessing it’s because it’s the next string or something 🤷🏻 
Anyway, test added & bug sqooshed
Test added; was failing before
No docs needed

Import meta env

---

.changeset/short-points-report.md
internal/token.go
internal/token_test.go

- This ended up being a pretty small change in the tokenizer, basically to ignore the current logic that any `<` characters should start an element.
- Didn't remove any logic from the parser/renderer that might handle this case. Those are dead code paths now, can cleanup later.
Existing tests updated to reflect our new approach
N/A

fix: drop JSX/TSX support from Frontmatter

---

.changeset/new-weeks-mix.md
internal/node.go
internal/parser.go
internal/printer/printer.go
internal/transform/transform.go

- In https://github.com/snowpackjs/astro-compiler-next/pull/146 I make the `Metadata` type a pointer in order to fix the `\x00` issue, however since this object is checked in the printer it needs to be initialized. This would mean ever time we create a Node (which happens all over in the parser) we would also need to create a Metadata.
- Instead this moves those slices back onto the top-level Node object, to prevent this.
Tests in Astro are broken, no idea why these tests are passing. Probably a wasm specific issue.
N/A

Remove metadata type

---

.changeset/new-socks-punch.md
internal/token.go
internal/token_test.go

Supersedes https://github.com/snowpackjs/astro/issues/1833
- Previously, comments and strings weren't being handled inside of expression attributes
- We also weren't able to support comments inside of a tag, but now we can (because they're expression attributes)
Tokenizer tests added
Bug fix

fix: comments and strings inside of expression attributes

---

.changeset/heavy-masks-jump.md
internal/parser.go
internal/transform/transform.go
internal/transform/transform_test.go

- In most cases, our parser is smart enough to detect when the only element is a `Component` node and skip generating the implied `html`, `head`, and `body` tags. This happens if the `Component` comes first.
- If there is a `style` or `script hoist` tag above the `Component` node, our parser isn't able to lookahead and determine if `html`, `head`, and `body` should be generated. They always are. 
- This PR adds a `transform` step that corrects the parser output. This happens here because this is the step where we walk the document and make any mutations based on contextual information.
New test suite added to `transform`
Bug fix

Fix leading `style` and `script hoist`

---

.changeset/spotty-buckets-accept.md
internal/parser.go
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Closes https://github.com/snowpackjs/astro/issues/1939
- We weren't handling expressions inside of the `table` or `tbody` insertion modes, which was causing expressions to be fostered to another parent.
- This PR implements expression handling inside of the `table` and `tbody` insertion modes. Importantly (not reflected in original report) this change will not create an implicit `tbody` or `thead` if the only child of `table` is an expression.
Tests added
Bug fix only

fix: expressions inside of `<table>`

---

.changeset/chatty-masks-check.md
internal/transform/scope-css.go
internal/transform/scope-css_test.go

- Closes https://github.com/snowpackjs/astro/issues/1942
- Updates our scoping approach to ignore `*` characters inside of functions.
- Test added
- Bug fix only

fix: do not scope `*` inside of `calc()` expressions

---

.changeset/good-eels-raise.md
internal/printer/printer.go
internal/printer/printer_test.go
internal/printer/utils.go

- Closes https://github.com/snowpackjs/astro/issues/1951
- Currently, attributes unescape entities, which is fine. We just weren't re-escaping `"` back to `&quot;` inside of attributes. Now we are!
Test added
Bug fix only

Fix escaped entities

---

.changeset/brave-comics-rush.md
internal/parser.go
internal/printer/printer_test.go

- Closes https://github.com/snowpackjs/astro/issues/1953
- Added a failing test, then made sure it passed.
- Added a fix that reset the `originalIM` if we hit `StartTagToken` inside of `inBodyIM` when `originalIM != nil`. We now properly handle this edge case.
Test added
Bug fix only

Fix `form > textarea` insertion mode

---

.changeset/gorgeous-islands-hunt.md
internal/printer/printer_test.go
internal/token.go

- Closes https://github.com/snowpackjs/astro/issues/1974
- Turns out not all of our tag checks were case-sensitive, so `Base` was being treated as a void tag (`base`).
- This fixes the case-sensitivity of the tokenizer.
Test added. Test that _was_ passing but should have been failing updated to reflect the correct behavior.
Bug fix only.

fix: make all element checks case sensitive

---

.changeset/dirty-starfishes-bake.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Fixes issue where only one script or style may be added from an Astro component.
- **Reason**: Astro Compiler spreads arguments to `Set#add` which takes one argument and not a spread.
- **Solution**: Iterate scripts or styles and add them individually to their respective set.
Tests are updated in `printer_test.go`
I would love to learn how I could write a specific test that would have caught this issue.
bug fix only

Fix issue where components can only add one style or script

---

.changeset/perfect-terms-rush.md
internal/parser.go
internal/printer/printer_test.go

- Fixes an issue where expressions did not work within SVG elements.
- Follows behavior of `inBodyIM`.
- added simple test — `<svg>{title ?? null}</svg>`.
- added nested test — `<svg>{title ? <title>{title}</title> : null}</svg>`.
bug fix only

Support expressions in SVG elements

---

.changeset/short-chairs-attack.md
cmd/astro-wasm/astro-wasm.go
lib/compiler/test/empty-style.test.mjs
lib/compiler/test/test.mjs

- In most places, empty `<style />` was accounted for.
- In `preprocessStyle`, we were unconditionally accessing the `FirstChild`.
- Added a WASM test for this, since that's the only way to hit this case.
JS/WASM test added
Bug fix only

fix: handle empty preprocessed style

---

.changeset/dry-years-impress.md
internal/node.go
internal/parser.go
internal/print-to-source.go
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/transform/transform.go
internal/transform/transform_test.go
internal/transform/utils.go

- Closes https://github.com/snowpackjs/astro/issues/1989
- The problem here was a regression in the handling of leading `<script hoist>` or `<style>` nodes (implemented in https://github.com/snowpackjs/astro-compiler/pull/154)
- The fix required two changes:
- Tracking which elements are implicitly generated while parsing the document.
- Being more intelligent about repairing a document after elements have been hoisted out
Many tests added
Bug fix only

Fix leading `<style>` regression

---

.changeset/small-beds-perform.md
cmd/astro-wasm/astro-wasm.go
internal/parser.go
internal/token.go
internal/transform/transform.go
lib/compiler/test/body-fragment.test.mjs
lib/compiler/test/component-only.test.mjs
lib/compiler/test/test.mjs

- Fixes https://github.com/withastro/astro/issues/2031
- Allows `body` and `head` (any arbitrary tag) inside of components when using `as: "fragment"`.
- This may become the default behavior (eventually).
WASM test added as that's the only area this behavior is surfaced
Bug fix

feat: implement new `fragment` behavior to support `head` and `body`

---

CONTRIBUTING.md
Makefile

The code does not need to be checked out under GOPATH to build.
Remove unneeded pkg/ prerequisites in Makefile, and references to GOPATH from the docs.
With new Go versions and using modules, packages don't need to be checked out under GOPATH.
make astro
make astro-wasm
this affects dev docs only.

Remove GOPATH references.

---

.changeset/stale-hornets-add.md
cmd/astro-wasm/astro-wasm.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go
lib/compiler/shared/types.ts

- Passes `projectRoot` through to the `createAstro` function in internals.
- This will be used to make URLs created by `Astro.resolve` be projectRoot relative
- `/src/...` instead of `/Users/name/...`
Tested in Astro mostly, tests updated here.
N/A

Pass projectRoot through to `createAstro`

---

internal/transform/scope-css_test.go

I was tracking down some compiler weirdness with CSS and wanted to add some tests for invalid CSS. Fortunately, these pass! So I think it’s worth adding just to track against regressions here.
No code changes.
test only
no docs

Add invalid CSS tests

---

.changeset/polite-planes-shake.md
Makefile
internal/parser.go
internal/token.go
lib/compiler/test/script-fragment.test.mjs
lib/compiler/test/slotted-api.test.mjs
lib/compiler/test/test.mjs
lib/compiler/test/top-level-expression.test.mjs

- Fix infinite loop in `fragment` mode
- Expressions were not being handled inside of `template`, which was causing an infinite loop on top-level expressions without a parent element.
WASM test added
Bug fix only

Fix expressions inside `<template>`

---

.changeset/calm-scissors-float.md
internal/parser.go
internal/printer/printer_test.go

- This was a fun one to track down!
- We shouldn't call `reconstructActiveFormattingElements` when we encounter a `StartExpressionToken`!
Test added
Bug fix only

Fix do not reconstruct active formatting elements on expression start

---

.changeset/unlucky-queens-accept.md
internal/parser.go
internal/printer/printer_test.go

- `XElement` was breaking because it had an expression with a `script` in it.
- This fixes that edge case
Minimal test added
Bug fix only

Fix edge case with conditional scripts

---

.changeset/happy-bikes-hug.md
internal/token.go
internal/token_test.go

- Fixes #199
- We had an edge case where Fragment shorthand syntax (`<>`) was not properly handled inside of an expression with preceding text.
- The fix was to return the preceding text as a `TextToken` _before_ consuming the `StartTagToken`.
Minimal test case added
Bug fix only

fix(#199): fragment shorthand syntax with preceeding text

---

internal/token_test.go

- Closes #197 
- No code changes
- Adds regression test to ensure Tokenizer can handle Markdown code block
Test only

test(#197): add test for Markdown codeblock

---

.changeset/short-bats-hammer.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/token_test.go

- Closes #198
- Treats `{}` as valid to avoid generating invalid JS when encountered
- It is treated equivalent to `{undefined}`
Curious what folks think the correct behavior is here? Should we handle this as `${undefined}` or `${}` (invalid JS) or throw a panic?
Tests added
No docs, this isn't an official feature

fix(#198): improve empty attribute behavior

---

.changeset/large-owls-serve.md
internal/transform/scope-css.go
internal/transform/scope-css_test.go

- Fixes #223
- Improves our scoping algorithm to not touch values inside of declaration rules (like `grid-template-column`.
Test added
Bug fix only

fix(#223): Do not prefix values inside of declarations

---

.changeset/forty-pillows-sleep.md
internal/transform/scope-css.go
internal/transform/scope-css_test.go

- Fixes #213
- Previously, any rules following `@keyframes` would not be scoped. This fixes that!
Multiple tests add
Bug fix only

fix(#213): @keyframes breaks following scoping

---

.changeset/red-olives-camp.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Closes #225
- Removes `noscript` from the list of tags to tokenize as raw text
Tests added in tokenizer and printer
Bug fix only

fix(#225): Do not treat `noscript` as raw

---

.changeset/twenty-gorillas-burn.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Closes #224
- Fixes logical error in expression tokenization step. It worked in most situations but #224 was a reproducible edge case where it failed.
Added tokenizer and printer tests to verify that the case in the issue works. Existing tests ensure this is not a regression.
N/A, bug fix only.

fix(#224): address issue with expression tokenization

---

.changeset/fair-goats-obey.md
internal/token.go
internal/token_test.go

- Closes #221
- Fixes tokenization of expression attributes when `/` is used (now breaks on closing `}`, if it exists)
Tests added
Bug fix only

fix(#221): fix tokenization of `/` inside expression attributes

---

.changeset/lucky-cups-rhyme.md
internal/parser.go
internal/printer/printer_test.go

- Closes #235 
- Fixes edge cases with expressions inside of `<table>` children (which have their own insertion mode).
Test added
Bug fix only

Improve handling of expressions inside of `<table>`

---

.changeset/odd-kiwis-shave.md
internal/parser.go
internal/printer/printer_test.go
internal/token_test.go

- Fixes #238
- This fixes an issue where `setOriginalIM()` was throwing because it was already set
Tokenizer test added to protect against regressions, printer test added to verify behavior
Bug fix only

Fix `textarea` edge case

---

.changeset/ninety-yaks-hide.md
internal/printer/print-to-js.go
internal/printer/printer.go

- Changes createAstro from `createAstro(import.meta.url)` to `createAstro("/src/components/Foo.astro")`.
- This aligns with what createMetadata receives.
- This is needed because in the static build (and eventually SSR) `import.meta.url` points to the build JS files and not the original source location. Since we want to resolve browser URLs, passing the pathname string makes more sense.
No tests needed updating
N/A

Pass opts.Pathname to top-level createAstro

---

.changeset/poor-bears-check.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Closes https://github.com/withastro/compiler/issues/242 and https://github.com/withastro/astro/issues/2346
- Fixes logic error in `data-astro-raw` detection
Multiple tests added
Bug fix only

Fix data-astro-raw logic

---

.changeset/silly-laws-smoke.md
cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
lib/compiler/shared/types.ts

- This adds hoisted scripts to the `TransformResult`. In the static build these will work like styles, where in dev they are all external. For example `/src/components/Counter.astro?astro&type=script&index=0` will be one path.
- A change on the Astro side will bundle these in production (static build only).
No added tests needed, only a change to the wasm API.
N/A

Add hoisted scripts to TransformResult

---

.changeset/shiny-singers-call.md
lib/compiler/shared/types.ts

- Small improvement for the types on hoisted scripts in the TransformResult. Makes it so that if you know the `type` then the corresponding other prop is not possibly undefined.
N/A
N/A

Better hoisted script types

---

.changeset/gentle-tips-lick.md
internal/token.go
internal/token_test.go

- Fixes #250
- updated string handler within raw_with_expression_loop in tokenizer, i believe that we need only to handle '`' rather than also handling '\\'' and '"'.
two tests were added to check if it will tokenize titles with quotes properly. 
bug fix only

Fix #250: Update string handler

---

.changeset/wicked-forks-do.md
cmd/astro-wasm/astro-wasm.go
internal/print-to-source.go
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/transform/transform.go
internal/transform/transform_test.go
internal/transform/utils.go
lib/compiler/shared/types.ts
lib/compiler/test/body-fragment.test.mjs
lib/compiler/test/extract.test.mjs
lib/compiler/test/script-fragment.test.mjs
lib/compiler/test/top-level-expression.test.mjs
lib/compiler/test/visible.test.mjs

- Partially implements https://github.com/withastro/rfcs/blob/main/active-rfcs/0007-finalize-head-body.md
- Removes `as: 'document'|'fragment'` special casing from the compiler
- Removes implicitly generated tags from the compiler output. What you author is what you get.
Tests have been updated to reflect new behavior (no implicit `<html>`, `<head>`, or `<body>` tags)
No docs yet

Treat all documents as fragments which generate no implicit tags

---

.changeset/tasty-garlics-call.md
.github/workflows/ci.yml
.github/workflows/release.yml
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go

- Uses new `renderHead` util to render out hoisted elements.
Tests will be updated
N/A

[DO NOT MERGE] add `renderHead` util to output

---

internal/parser.go
internal/printer/printer_test.go

- Fixes https://github.com/withastro/compiler/issues/272
- Self-closing tags were being removed from the open elements stack (`p.oe`) but continued to be added to the active formatting elements (`p.afe`) stack!
- This fixes the handling of self-closing formatting elements (`a`, `b`, `big`, `code`, `em`, `font`, `i`, `s`, `small`, `strike`, `strong`, `tt`, `u`, and `nobr`)
Test case from issue added
Bug fix only

Acknowledge self-closing formatting elements

---

.changeset/young-masks-cover.md
internal/token.go
internal/token_test.go

- Closes https://github.com/withastro/compiler/issues/277.
- Improves Astro's `MathML` support by treating `{}` characters as raw text. 
- Note that this introduces a new tokenization mode where _only expressions are disabled_. All children are still tokenized properly, but `{` is a `TextToken` rather than `StartExpressionToken`. This means that Astro compiler directives like `set:html` will continue to work inside of `<math>`.
- There are likely few users impacted by this change directly, but more users who use something like [KaTeX](https://katex.org/) (where `{}` represent significant characters) that will benefit from this indirectly.
Tokenizer tests added!
Bug fix. Should this be documented somewhere?

Treat `{}` as raw text inside of `<math>`

---

.changeset/perfect-chefs-invite.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Closes #251.
- Nested template literals weren't being handled properly inside of Attribute expressions. Specifically, we had no logic to track them, so the `/` character would trigger an unexpected code flow.
- This PR updates the attribute tokenizer to be aware of template literals and properly tokenize nested template literals.
Tokenizer and printer tests added
Bug fix only

Fix nested template literal expressions in attributes

---

.changeset/yellow-kids-walk.md
internal/printer/printer.go
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Was investigating an issue with `data-astro-raw` that turned out to not be a problem with the compiler! Woohoo!
- This formalizes support for `data-astro-raw` attribute as the `is:raw` directive.
- `is:raw` attribute will not be printed in the output, it is just a compiler directive.
Tests added
TBD.

feat: `data-astro-raw` => `is:raw`

---

.changeset/nine-cheetahs-act.md
internal/parser.go
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/token_test.go

- Closes https://github.com/withastro/compiler/issues/284
- Fixes conditional rendering of special elements like `iframe` and `noscript`.
- These were setting the parser `context`, which then meant `p.im()` would throw.
Tests added
Bug fix only

Fix conditional special elements

---

.changeset/wise-elephants-kiss.md
internal/printer/printer.go
internal/printer/printer_test.go

- The static build uses the hoisted metadata to track which hoisted scripts are part of a page, in order to build them.
- This fixes it so that expressions are passed as the variable and not quoted.
- Part of https://github.com/withastro/astro/issues/2604
Test added
N/A

Fixes hoisted scripts passed a variable

---

.changeset/rich-gifts-change.md
lib/compiler/browser/index.ts
lib/compiler/node/index.ts

- Previously, a bug caused us to instantiate multiple instances of the compiler
- Combined with our larger WASM output, v0.11.0 may have made an existing memory issue even worse
- Tested in examples/blog-with-multiple-authors (3 markdown pages) and reduced 7 calls to instantiation down to 1. Seemed to have some noticeable impact on build time from 3sec -> 2.5 (hard to replicate reliably, so take that with a big grain of salt).
- N/A

fix memory usage caused by duplicate instantiations

---

.changeset/moody-horses-greet.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Fixes our handling of elements like `<title />` and `<script />`.
- These cases were very unlikely before, but with the introduction of `set:text` and `set:html` they are much more likely.
- This was a change needed in the tokenizer because `<title />` would read everything following as raw text since it never encountered a closing `</title>` tag.
Tests added
Bug fix only

Handle self-closing raw elements

---

.changeset/unlucky-swans-destroy.md
internal/transform/transform.go
lib/compiler/test/hoist-expression.test.mjs

- Adds a warning when doing `<script hoist src={expr}></script>`.
- That's because we need to statically resolve these, explained here: https://github.com/withastro/astro/issues/2648
mjs test added
N/A

Warn when using an expression on hoist `src` attr

---

.changeset/quick-lamps-stare.md
internal/printer/printer.go
internal/printer/printer_test.go
lib/compiler/test/render-head.test.mjs

- Previously, we injected a `renderHead` util inline. This only worked sometimes because we `Promise.all()` the children and there was a race condition.
- Now, the compiler injects a `` placeholder which can be swapped out at render time.
Test added. Also tested manually in monorepo.
N/A

Improve `renderHead` behavior

---

.changeset/rare-snakes-heal.md
lib/compiler/package.json
yarn.lock

Move TS to devDependencies, shouldn't be needed as a production dependency for the compiler.
Tested by running `yarn build` in lib/compiler, not sure if more is needed.
Internal dependency change only.

Move `typescript` dependency to development dependencies

---

.changeset/afraid-elephants-live.md
lib/compiler/browser/utils.ts
lib/compiler/node/utils.ts
lib/compiler/shared/ast.ts

- Updates the `parse` AST utils to include `fragment` guard
- Adds `FragmentNode` interface definition
N/A, type change only
N/A

Update AST to include `fragment`

---

.changeset/wise-scissors-raise.md
go.mod
go.sum
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go
internal/token_test.go

- Fixes #323! For real this time.
- Turns out JS tokenization needs some context to properly tokenize RegExp literals (`/=/` or `/a/` or `/\./`)
- We weren't handling these properly, because we needed to call `l.RegExp()` to walk the tokenizer back and reconsume the following content as RegExp.
- Added tests for reported issue, no longer hangs and works as expected
- Added test to ensure there wasn't a regression if `/` was not a RegExp literal but just division.
Bug fix only

Properly handle RegExp literals in `js_scanner`

---

.changeset/khaki-bulldogs-reflect.md
internal/parser.go
internal/printer/printer_test.go

- Fixes https://github.com/withastro/astro/issues/2951, fixes https://github.com/withastro/astro/issues/2904
- We had a bug in the logic that handled inserting a `slot` inside of the `head` element.
- This PR fixes the bug by not switching the parser to `inBodyIM`, but keeping the parser in `inHeadIM` after encountering a `slot` element.
Test added
Bug fix only

Do not switch to `inBodyIM` when encountering slots in the `head`

---

.changeset/good-bugs-help.md
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/transform/scope-css.go
internal/transform/transform.go
internal/transform/transform_test.go
internal/transform/utils.go

- Implements [RFC0016](https://github.com/withastro/rfcs/blob/main/proposals/0016-style-script-defaults.md)
- Adds support for `is:inline` and `is:global`
- Companion PR to https://github.com/withastro/astro/pull/2961
Tests updated
Covered by core PR

Support new script/style behavior

---

.changeset/real-plums-wonder.md
internal/printer/printer.go
internal/printer/printer_test.go

- Fixes https://github.com/withastro/astro/issues/3017
- Our client-only detection was only picking up on the last component due to the use of `break` in the loop. This PR fixes that by switching to `continue loop`.
Test added
Bug fix only

fix: multiple client-only components

---

.changeset/slow-dragons-deliver.md
internal/parser.go
internal/printer/printer_test.go

- Previously, `<tr>` (and a few others) at the top level would not be printed.
- Now they will. Removed code that ignored these elements.
- Closes #343, #351
Test added
Bug fix only

fix(#343): orphan table elements in body

---

.changeset/popular-toys-cough.md
internal/parser.go
internal/printer/printer_test.go
internal/token_test.go

- Fixes https://github.com/withastro/compiler/issues/340
- Markup after `inSelectIM` would be ignored. Now we switch back to `inBodyIM` when we encounter any unhandled element.
Tests updated
Bug fix only

fix(#340): reset insertion mode on invalid tags when inSelectIM

---

.changeset/rude-bulldogs-listen.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/printer/utils.go
internal/token.go
internal/token_test.go

- Adds support for expressions that only contain a comment block
- `{/* a comment */}`
- Adds support for comments in Shorthand
- `<h1 {/* comment in shorthand */ id}>Hello</h1>`
- Adds support for Shorthand attributes that only contain a comment
- `<h1 {/* id={prop commentd out} */} class={class}>Hello</h1>`  
- Adds panic when a comment block is unterminated (missing `*/`)
See tests https://github.com/withastro/compiler/pull/364/files#diff-d0dbf4b902747f2cdc45290c88eb59b04d03bebcb2bd8872a0b49284a9dac9d1R1810
Tests added for
- Comment only expressions
- Comments in attributes/props
- Panic when a comment block is unterminated
I don't think we need to add this to docs explicitly

Add support for comment block only expressions and comment blocks in attributes and props

---

.changeset/nice-bulldogs-unite.md
internal/parser.go
internal/printer/printer_test.go
internal/token_test.go

- Fixes https://github.com/withastro/compiler/issues/366
- There was an edge case where we'd return to `inSelectIM` from `inExpressionIM` but then we never left `inSelectIM`.
- This PR changes it so that we go `inSelectIM => inExpressionIM => inBodyIM`.
Test added, our current coverage didn't catch this.
Bug fix only

Fix `<select>` elements with expression children

---

.changeset/six-squids-wink.md
internal/printer/print-to-json.go
internal/printer/printer_test.go

Fixes #380
This PR fixes `escapeForJSON` to escape the backslash (`/`).
I added a test case for a template with backslashes to `internal/printer/printer_test.go TestPrintToJSON` and verified that `go test -v ./internal/...` command passed.
bug fix only.

fix(#380): fix json escape

---

.changeset/hip-games-trade.md
internal/transform/scope-html.go
internal/transform/scope-html_test.go

- Injected `astro-XXXXXX` when `class:list` is used instead of `class`
- Fixes #391 
Tests updated
Bug fix only

fix(#391): inject astro scoped class when `class:list` is used

---

.changeset/chilly-chairs-enjoy.md
cmd/astro-wasm/astro-wasm.go
internal/transform/transform.go
internal/transform/transform_test.go

This makes it so that newlines at the end of files are not considered. This is because it can lead to confusing behaviour; defining an Astro component with a newline at the end (which can be implicitly placed by most editors) adds an implicit newline to the final output, resulting in strange spaces in the final HTML.
For example:
```astro
<a href={Astro.props.href}><slot /></a>
```
```astro
---
/* src/pages/index.astro */
import Link from '../components/Link.astro';
---
<p>this is a <Link href="example.com">test</Link>!</p>
```
results in a strange space between the link text and the exclamation mark:
This change simply makes it so that the three exposed JS functions all strip newlines from the end of the source text before attempting to use it.
This was manually tested. Does this need …

fix: strip newlines at the end of component files

---

.changeset/shiny-dots-care.md
internal/printer/printer.go
internal/printer/printer_test.go

- The compiler adds import statements for each user import in order to figure out which one maps to a component.
- CSS side-effectual imports should *not* be included in this metadata. Doing so prevents CSS try shaking this code away.
- This is part of switching to Vite's internal CSS plugin and fixing https://github.com/withastro/astro/issues/2146
- Test added
N/A, bug fix.

Prevent including module metadata imports for side-effectual CSS

---

.changeset/tame-eyes-provide.md
packages/compiler/node/utils.ts
packages/compiler/test/parse/serialize.ts

This PR fixes the wrong serialize when it has a spread attribute in `utils`'s `serialize` method.
This fix is related to https://github.com/withastro/prettier-plugin-astro/issues/193.
I have added the spread attribute to the serialize test case template.
bug fix only.

fix: fix serialize spread attribute

---

.changeset/bright-panthers-hang.md
cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/printer/printer.go
internal/transform/transform.go
packages/compiler/shared/types.ts
packages/compiler/test/basic/component-metadata/index.ts

- Includes component metadata as part of the transform result: `hydratedComponents` and `clientOnlyComponents`. This includes the specifier, resolvedPath, and exportName.
- This information will be used by the build to know what client JS needs to be built, without running the code in dev SSR mode as we do today.
- Tests added
N/A

Include component metadata in the transformResult

---

.changeset/happy-vans-fetch.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Previously, we would throw if the `slot` attribute was used outside of a component or `custom-element`.
- Given projects like OpenUI's upcoming [`select`](https://open-ui.org/components/select), standard elements may soon support slots. We need to support this.
- This PR preserves `slot` attributes **unless** the immediate parent is a component. This matches existing behavior **and** unblocks standard uses for the `slot` attribute.
- This PR adds `is:inline` support for the `slot` element. Instead of replacing this with slotted contents, we will literally print `<slot />`. This unblocks standard use cases for the `slot` element.
Printer tests added.
TODO

Preserve `slot` attribute outside of component, support `<slot is:inline />`

---

.changeset/twenty-snakes-punch.md
internal/printer/printer_test.go
internal/transform/scope-html.go

- Fixes https://github.com/withastro/astro/issues/3823
- For historical reasons, `body` was not scoped and `html` had inconsistent behavior.
- Now `html` and `body` are scoped like any element.
Relevant tests updated
Bug fix only

fix(#3823): scope html and body elements

---

.changeset/hungry-spoons-crash.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go

- Closes #383, #352, #388
- Paired with `astro` PR https://github.com/withastro/astro/pull/3837
- Fixes support for the `slot` attribute inside expressions
- Previously, we treated `{}` as an opaque element, so any children with the `slot` attribute were not transformed.
- Now, we dive into the `{}` expression to identify any children with a `slot` attribute and bubble them up.
- Introduces `mergeSlots` util that recursively merges the results of function expressions into the `slots` object
Tests added
Bug fix only

Support slot attribute inside expressions

---

.changeset/eight-teachers-sniff.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Discovered a bug in the course of fixing https://github.com/withastro/compiler/pull/447
- Fixes edge case with multiple nested expressions
- The tokenizer has some rough heuristics around when braces start an expression vs when they act as raw text
- Previously, `StartTagToken` and `EndTagToken` would reset these heuristics
- This PR implements a simple stack for `StartTagToken` and `EndTagToken` that determines if we're inside elements (`{` === `StartExpressionToken`) or outside of them (`{` === `TextToken`)
Multiple test cases added
Bug fix only

Handle nested expressions edge case

---

.changeset/stale-birds-clean.md
internal/transform/transform.go
packages/compiler/test/client-directive/warn.ts

- Adds a warning when using a `client:` directive on a script.
- Added a test, but unable to specifically capture the warning in a test. Tried overriding console.log/warn/error, I think Go might be pushing to `stdout` directly. However you can see that the warning does occur when running the test.
N/A

Warn on client: usage with scripts

---

.changeset/serious-mayflies-sniff.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

- Fixes nested expression bug by reverting #448 
- Patch release, will follow-up with correct implementation
Tests pass
Bug fix only

Revert #448

---

.changeset/proud-cheetahs-sort.md
internal/token.go
internal/token_test.go

- Fixes #424 
- Properly handle unmatched `}` inside template literals
Tests added
Bug fix only

Fix unmatched closing brace in template literal

---

.changeset/good-pears-chew.md
cmd/astro-wasm/astro-wasm.go

- This removes the default/fallback for `site`, because you have to provide that value now and we want `Astro.site` to be undefined if no value is provided.
- Tested in withastro/astro proper.
N/A

Remove site default

---

.changeset/healthy-books-fetch.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts

Much like attributes containing `@`, attributes containing dots are not supported in TSX. A common usage of them is Alpine's events, ex: `<input type="text" x-on:keyup.shift.enter="alert('Submitted!')">` so they need to be moved to a spread
Added a test
N/A

Move attributes containing dots to spread in TSX output

---

.changeset/twenty-spoons-perform.md
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go

- Reworks our logic to automatically hoist all imports in a file to the top
- Removes confusing `FindRenderBody` heuristic that caused some weird edge cases
- Improves `getStaticPaths` hoisting (properly handles RegExps
- Improves `js_scanner` test coverages
- Removes dead code, including an old `skipHoist` workaround in our tests
- Improves output consistency across the board
- Closes https://github.com/withastro/compiler/issues/354
- Closes https://github.com/withastro/compiler/issues/195 (our oldest issue!)
- Tests for `js_scanner` updated.
- `printer` tests updated to remove old `skipHoist` workaround
Will open a PR to remove this warning from the docs! 🎉 
https://github.com/withastro/docs/pull/1001

Remove limitation that imports must be at the top

---

.changeset/hot-rings-burn.md
internal/token.go
internal/token_test.go
internal/transform/transform.go
packages/compiler/test/basic/trailing-space.ts
packages/compiler/test/parse/serialize.ts

- Removes special Markdown component parsing, need to use `is:raw` in the future.
- Tests updated
N/A

Remove Markdown special-casing

---

.changeset/shaggy-sheep-pump.md
internal/printer/printer_test.go
internal/transform/transform.go
internal/transform/utils.go

- Supercedes https://github.com/withastro/compiler/pull/396
- Closes https://github.com/withastro/compiler/issues/395
- Does not hoist `script` or `style` elements inside of `noscript` or `template` nodes
Tests updated
Bug fix only

Do not hoist `script` or `style` inside of `noscript` or `template`

---

.changeset/yellow-pots-fry.md
cmd/astro-wasm/astro-wasm.go
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/scope-css.go
internal/transform/scope-html.go
internal/transform/transform.go
internal/transform/utils.go
packages/compiler/shared/types.ts

- Update output to wrap `define:vars` scripts with a scope (`{}`), so we can redeclare variables
- Update output to inject `define:vars` styles directly into each top-level element's `style` attribute
- Improve sourcemaps for hoisted `script`
- Blocks https://github.com/withastro/astro/pull/3976
Tests updated
Bug fix only

Fix `define:vars`

---

.changeset/strange-badgers-exist.md
cmd/astro-wasm/astro-wasm.go
internal/hash.go
internal/print-to-source.go
packages/compiler/shared/types.ts
packages/compiler/test/styles/emit-scope.ts
packages/compiler/test/styles/hash.ts

- Updates hashing algorithm to **ignore** the contents of hoisted `<style>` blocks.
- This will make style HMR significantly easier, since we won't have to update all the `class` attributes in the DOM
Tests added. Only happens in `transform` so these are JS tests.
Internal change only

Stable scoped class

---

.changeset/blue-deers-beam.md
internal/printer/printer_test.go
internal/token.go

- Prevents unescaping expression attribute values. 
- Fixes https://github.com/withastro/astro/issues/3916
- Test added to ensure the markdown Fragment set:html condition holds.
N/A

Prevent unescaping expression values

---

.changeset/wet-socks-glow.md
internal/printer/printer.go
internal/printer/printer_test.go

- New `define:vars` logic wraps the entire script with `{ }` to create a scope to prevent global errors.
- Module scripts are already scoped, and adding `{ }` around them causes errors because `import` cannot be inside of a scope.
- This now makes it so that module scripts are not wrapped.
- test added
N/A, bug fix.

Prevent wrapping module script with scope

---

.changeset/nervous-jobs-live.md
internal/token.go
internal/token_test.go

- Closes https://github.com/withastro/astro/issues/4122
- Skip handling quotes when inside a template literal
Tokenizer tests added

Handle unbalanced quotes in expression attributes

---

.changeset/bright-socks-change.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Prevents printing the doctype, just in the JS output. The astro runtime already prepends the doctype all of the time.
- Part of https://github.com/withastro/astro/issues/4166
- Tests updated that expected the doctype to be printed.
N/A

Prevent printing the doctype in the JS output

---

.changeset/fast-rules-fix.md
internal/printer/printer_test.go
internal/token.go

- Fixes issue outlined in https://github.com/withastro/astro/pull/4175#issuecomment-1206863934
- When checking for generics, we should probably check that the expression length isn't `0`. This is the fix!
Test added
Bug fix only

Fix regression in generics logic

---

.changeset/dirty-rice-work.md
internal/printer/printer_test.go
internal/transform/transform.go
packages/compiler/test/basic/component-metadata/index.ts

- Companion PR to https://github.com/withastro/astro/pull/4272
- Updates how we match namespaced `components.with.deep.members`.
- Properly match `*` exports and `import { components } from 'file'`
- Removes `$$metadata` matcher utils which are mostly dead code paths now. With this PR, they can probably be removed from the frontend!
Tests updated
Bug fix only

Better handling for namespaced components

---

.changeset/thin-beers-ring.md
internal/printer/printer_test.go
internal/transform/transform.go
packages/compiler/test/basic/component-metadata/index.ts

- https://github.com/withastro/compiler/pull/497 removed the need for `metadata.resolveSpecifier`, but there was code in that path that trimmed `.jsx` from a specifier.
- This moves that logic into the compiler to match existing behavior
- Without this, builds will fail!
Tests updated
Bug fix only

Fix resolution of JSX modules

---

.changeset/gorgeous-zoos-think.md
internal/printer/print-css.go
packages/compiler/test/static-extraction/css.ts

Fix #502 
I may be missing something big, but it doesn't seem like CSS needs to be escaped as it's not JS 🤔 I've removed it for CSS printing for static extraction
Added test to `css.ts`
N/A

Remove css print escape for experimentalStaticExtraction

---

.changeset/gorgeous-cooks-jog.md
internal/js_scanner/js_scanner.go
internal/printer/printer_test.go

- For https://github.com/withastro/astro/issues/4632
- The js scanner was looking for `assert` as an identifier anywhere in the statement, but it should only look after we've scanned the specifier.
- Test added
N/A, bug fix.

Fix assertion parsing to always happen after the specifier

---

.changeset/tricky-mugs-wash.md
internal/printer/print-to-js.go

- Changes it so that we print out our Astro CSS style imports *after* frontmatter imports. With the Astro CSS imports being last they will be added last in dev and build, and therefore take priority.
- Tested manually in example project.
- Will add fixture tests in astro core
Bug fix

Make Astro styles being printed after user imports

---

.changeset/proud-peas-pull.md
internal/js_scanner/js_scanner.go
packages/compiler/test/basic/get-static-paths.ts

- Fixes various edge cases where `getStaticPaths` wouldn't be hoisted if there was a valid newline
- `js_scanner` now tracks seen tokens (like `function` and `=>`) to verify that we must also see a `{` token before closing.
- Tests were added for `function` and `const` style functions
- Closes [withastro/astro#4685](https://github.com/withastro/astro/issues/4685), #512 
Tests added

Fix `getStaticPaths` hoisting

---

.changeset/tricky-mugs-wash.md
internal/printer/print-to-js.go
packages/compiler/test/css-order/astro-styles.ts
packages/compiler/test/css-order/imported-styles.ts

- Brings back https://github.com/withastro/compiler/pull/520
- was reverted because it caused components with no frontmatter to not have their imports printed.
- This fixes that
- Tests added,
- testing that components without frontmatter have their css import.
- testing that components with frontmatter imports come before the component style import.
N/A, bug fix

Fix: CSS order for imported CSS vs. Astro styles

---

.changeset/seven-monkeys-try.md
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go

- Closes #508
- Properly handle `import.meta` when scanning for imports
Tests added, one for `import.meta.env` and one for `import\n.meta\n.env` usage
Bug fix only

Fix `import.meta` usage above normal imports

---

.changeset/dull-countries-taste.md
internal/transform/scope-css.go
internal/transform/transform_test.go

- Closes #516
- Empty styles (containing a string with only spaces) should not cause any markup to be scoped
Go tests added
Bug fix only

Fix empty style hashing markup

---

.changeset/pretty-windows-cheat.md
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/transform/transform.go

- Fixes a regression caused by https://github.com/withastro/compiler/pull/532
- Call insertBefore on the parent, not on the doc (oops).
- Closes https://github.com/withastro/astro/issues/4942
- New test added
Bug fix

Do not remove elements following a hoisted script

---

.changeset/silly-coats-fix.md
cmd/astro-wasm/astro-wasm.go
internal/parser.go
internal/printer/printer_test.go

- Closes https://github.com/withastro/compiler/issues/318
- Currently, parsing "corrects" markup according to the HTML spec.
- For our AST output, we should handle things more literally to avoid issues like https://github.com/withastro/prettier-plugin-astro/issues/260
- This adds a `literal` mode to the parser, which handles elements before and after `html` gracefully.
`print-to-json` tests added
Bug fix only

Add `literal` parsing option for AST/TSX

---

.changeset/nervous-ducks-fetch.md
internal/parser.go
internal/printer/printer_test.go

- Closes #531
- Fixes edge case where `slot` content was not picked up
Go test added

Handle `slot` before <head>

---

.changeset/quick-deers-kiss.md
internal/js_scanner/js_scanner.go
internal/printer/printer_test.go

- Closes #530
- Avoid hoisting `import` when followed by a `:` token (inside an object)
Test added
Bug fix only

Fix import hoisting edge case

---

.changeset/tidy-feet-join.md
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go

- Closes #536
- Handles edge case with multi-line export hoisting
- Ensures types and interfaces are handled similarly to functions
Test added
Bug fix only

Support multi-line export hoisting

---

.changeset/funny-elephants-bathe.md
internal/parser.go
internal/printer/printer_test.go

- Closes #519 
- Handle edge case where `noscript` tags were not being handled properly
- Removed `p.scripting` default of true because there's no JS when we're parsing
Test added
Bug fix only

Handle edge case with noscript tags

---

.github/workflows/snapshot-release.yml

Hopefully this can just work out of the box! I think there might be a couple of necessary secrets to set up but otherwise we might be good :thumbsup:
- Adds the `snapshot-release.yml` workflow, which will publish a snapshot release of a branch when `!preview snapshot-name` is posted in a PR comment. This requires that the comment was posted by an admin of the repo
Not sure how to test except for live 🤔

Copies `snapshot-release.yml` from withastro/astro

---

.changeset/witty-tools-turn.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/props.ts

- Closes https://github.com/withastro/compiler/issues/499
- Implements automatic typing for `Astro.props`
- Does not support generics, but that's okay
Tests updated
N/A, this is how it currently works

Auto type `Astro.props` interface

---

.changeset/slimy-fireants-kneel.md
internal/transform/transform.go
packages/compiler/test/parse/client-component-unfound.ts

Since 0.27.0, `parse` would crash on the following input:
```astro
{
// For best cross-browser support of sticky or fixed elements, they must not be nested
// inside elements that hide any overflow axis. The article content hides `overflow-x`,
// so we must place the mobile TOC here.
headers && (
<nav class="mobile-toc">
<TableOfContents
client:media="(max-width: 72em)"
headers={headers}
labels={{ onThisPage: t('rightSidebar.onThisPage'), overview: t('rightSidebar.overview') }}
isMobile={true}
/>
</nav>
)
}
```
I eventually tracked this down to [this line](https://github.com/withastro/compiler/blob/38b0ea446bcbdcb1b69be5f8108136d9e23e7b49/internal/transform/transform.go#L446), `doc.FirstChild.FirstChild` was `nil`. Adding a if check fixed the issue and made tests pass. 
Not sure if …

Fix parse crashing when a component with a client directive was unfound

---

.changeset/lemon-cars-brush.md
cmd/astro-wasm/astro-wasm.go
internal/sourcemap/sourcemap.go

- `astro:runtime` was introduced in the TSX sourcemap PR, but this was causing issues at runtime since Vite would log warnings about a missing sourcefile
- This PR removes the `astro:runtime` source (which did not exist)
Manually, fixes the warning
N/A

Remove non-existent sourcemap source

---

.changeset/mean-houses-draw.md
internal/token.go
packages/compiler/test/basic/comment.ts

- Fixes #565 
- We weren't handling `/***/` comments properly because we assumed the opening `/*` and closing `*/` would be separated. This fixes that.
Test added
Bug fix only

Handle comments with many * characters

---

packages/compiler/test/basic/lt-gt-text.ts

- Added regression test for `< header >` behavior as raw text
- Intentionally not including a changeset, this is internal only
It's all tests!
Bug fix only

Add test for text containing `<` and `>`

---

.changeset/six-owls-drop.md
cmd/astro-wasm/astro-wasm.go
internal/printer/printer.go
internal/transform/transform.go
packages/compiler/shared/types.ts
packages/compiler/test/resolve-path/preserve.ts

Add `resolvePath` option so we can control how hydration paths are resolved. This removes hacks made previously to undo the compiler path changes.
The Astro repo has [a branch](https://github.com/withastro/astro/tree/resolve-path-option) I'm working on integrating this PR, which is working nicely too.
Added a simple test for the new option.
It doesn't look like we have documentation for the optional options. I could send a PR to update the readme was this new option stabilizes, documenting along the other options.

Add `resolvePath` option

---

.changeset/thin-trains-remember.md
internal/printer/print-to-js.go
internal/printer/printer.go
packages/compiler/test/resolve-path/preserve.ts

Remove unused code, e.g.
```js
import * as $$module1 from './foo/bar'
export const $$metadata = $$createMetadata(...)
```
...when `resolvePath` option is provided. Metadata isn't used for anything else other than `$$metadata.resolvePath` which is only called if no `resolvePath` is provided.
The main Astro repo also isn't using the `$$metadata` export for anything else. I've tested this on [this branch](https://github.com/withastro/astro/tree/resolve-path-option).
The removal of `import * as` helps to remove [this patch](https://github.com/withastro/astro/blob/9d195b0921b446a80e0c4c893b6cf29bef14312d/packages/astro/src/core/build/vite-plugin-css.ts#L227-L257) which fixes a bug with `.css?raw` imports. 
---
This PR sprinkles if conditions around 😬 but once `resolvePath` is solidified, we …

Remove metadata export for `resolvePath`

---

.changeset/loud-pigs-fold.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts
packages/compiler/test/tsx/props.ts

- Self-closing tags were mapped to an end-tag that didn't exist.
- Now self-closing tags are maintained.
- Small mapping tweaks as well
New test added, old tests updated
Bug fix

TSX: improve self-closing tag handling

---

.changeset/long-planes-nail.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts

- Fixes edge case related to spread attributes like `{...Astro.props}` 
Test added
N/a

TSX: Ensure spread attributes are not treated as invalid

---

.changeset/forty-monkeys-drum.md
.github/workflows/ci.yml
internal/printer/printer.go
packages/compiler/test/tsx/non-latin.ts
pnpm-lock.yaml

We had some UTF8 compatibility issues with our output. The problem was that we were appending `[]rune` (`utf8` characters) to our `output` buffer but it was treated as if the values were `[]byte` instead. This fixes that by always converting to `[]byte` first before appending characters to `output`. There are a few other refactors for clarity.
Adds [this wonderful code](https://mathiasbynens.be/notes/javascript-identifiers) as a test case for our output
N/A

Fix utf8 compat

---

.changeset/young-pugs-retire.md
internal/parser.go
packages/compiler/test/parse/position.ts

- Closes https://github.com/withastro/compiler/issues/575
- Includes end location when `inLiteralIM`, which happens for `parse()`
Added a test
Bug fix only

Include end location in literal mode

---

.changeset/flat-apples-turn.md
internal/parser.go
packages/compiler/test/parse/position.ts

- Fixes `parse` AST to include end positions for `text` and `comment` nodes.
- Unblocks https://github.com/withastro/prettier-plugin-astro/pull/297
Test added

Ensure text/comment nodes have end positions

---

.changeset/ninety-cherries-guess.md
internal/printer/print-to-json.go

- Follow-up to #591
- Internally, the `start` position of elements is the beginning of the tag name.
- For our public AST, it should be the first index of the start tag.
- This updates our AST to use the first index of the start tag for element nodes.
Tested manually
Bug fix only

Move `start` position for elements

---

.changeset/tall-peas-sort.md
internal/loc/loc.go
packages/compiler/test/client-directive/warn.ts

- Closes https://github.com/withastro/compiler/issues/595
- Fix issue with diagnostic severity levels, would always return as errors (`1`)
Test updated
Bug fix only

fix(diagnostics): return proper diagnostic level

---

.changeset/seven-nails-compete.md
internal/printer/printer.go
internal/printer/printer_test.go

- Safari hoists function declarations out of a block scope, https://bugs.webkit.org/show_bug.cgi?id=179698
- This means that our use of block scope breaks any define:vars script (in Safari) that uses a function declaration.
- Part of https://github.com/withastro/astro/issues/5064
- Fix is to use an IIFE instead.
Tests updated.
N/A

Use an IIFE to scope define:vars scripts

---

.changeset/rude-cherries-turn.md
internal/printer/printer.go
internal/sourcemap/sourcemap.go
packages/compiler/test/tsx-sourcemaps/template-windows.ts

Removes some inherited logic that was specific to Windows, since it was actually causing this bug 🙃 
Adds Windows-style `\r\n` tests
Bug fix only

Improve TSX sourcemaps on Windows

---

.changeset/sour-toys-join.md
internal/loc/diagnostics.go
internal/printer/printer_test.go
internal/transform/scope-html.go
internal/transform/transform.go
internal/transform/utils.go
packages/compiler/test/errors/define-vars.ts

- Closes https://github.com/withastro/astro/issues/4400
- Adds a warning when `<style define:vars>` doesn't work because of limitations of static analysis.
Test added
Bug fix only

Add warning when unable to inject `define:vars`

---

.changeset/three-ligers-clap.md
internal/parser.go
internal/printer/printer_test.go

- Fixes #598, fixes #466
- Introduces some better `inLiteralIM` handling, where we can pass a custom function for exiting `inLiteralIM`. In this case, we exit `inLiteralIM` when the stack of open elements returns to the state it was in when we entered.
Both issues added as test cases
N/A, bug fix

fix(#598, #466): fix ternary expression edge cases

---

.changeset/thick-wombats-dance.md
internal/parser.go

- [Literal Insertion Mode handling](https://github.com/withastro/compiler/pull/617) introduced a regression for consumers using `parse`. Only caught this when `format` on Astro's main repo was hanging.
- This refactors `inLiteralIM` to ensure that the mode is exited properly when tokens are unhandled.
- Blocks https://github.com/withastro/prettier-plugin-astro/pull/305, https://github.com/withastro/astro/pull/5369
Tested locally in the `prettier-plugin-astro` repo, no more hanging
Bug fix only

fix: infinite loop regression in literal (parse/ast) mode

---

.changeset/cold-mice-stare.md
internal/parser.go
packages/compiler/test/basic/body-after-head-component.ts

- Will address https://github.com/withastro/astro/issues/5379
- `inLiteralIM` was being handled properly, but we forgot to set `p.originalIM` to `inHeadIM`, which was causing `body` tags to be disregarded
Test added
Bug fix only

fix regression for inLiteralIM handling

---

.changeset/heavy-mice-begin.md
internal/parser.go
packages/compiler/test/parse/position.ts

- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.
While attempting to use `prettier-plugin-astro` and self-closing HTML tags, I ran into this issue:
https://github.com/withastro/prettier-plugin-astro/issues/306
Here, we can see that our self-closing tag is not receiving an `end` positional data, unlike other tags.
To do this, we simply had to `push` a `loc` data into the `SelfClosingTag` token.
We can see a similar issue that occurred in:
https://github.com/withastro/compiler/pull/588
Which was fixed in a similar manner.
There are tests added in `position.ts` and I've verified this behavior in a manual Go debugger instance.
No docs are need, this was only a bug fix.

Self-closing tags now generate end position

---

.changeset/honest-lemons-pump.md
internal/loc/diagnostics.go
internal/printer/print-to-tsx.go
internal/token.go
packages/compiler/test/tsx-sourcemaps/unfinished-literal.ts

- Previously "<div foo=`></div>" would cause a panic
- Now this is properly handled and surfaces error
- In the TSX output, this is treated as `<div foo={``}></div>`
Test added
Bug fix only

Handle unterminated template literal attributes

---

.changeset/short-crabs-chew.md
cmd/astro-wasm/astro-wasm.go
packages/compiler/README.md

- Closes #408
- Update default `internalURL` as `astro/internal` is no longer used
- Now defaults to `astro/runtime/server/index.js`
Existing tests should pass
README was updated

fix: update default internalURL

---

.changeset/healthy-actors-occur.md
internal/loc/diagnostics.go
internal/token.go
packages/compiler/test/errors/invalid-spread.ts

- Closes #334
- Although attributes like `<Head ...seo />` are supported, they are most likely a mistake
- This PR adds a new warning for this, with a suggested fix (wrap the attribute in a `{}` expression).
Test added
N/A, QoL Improvement

Warn on invalid spread attributes

---

.changeset/giant-chairs-rest.md
internal/parser.go

- What does this change? 
Avoid nil pointer dereference in `inTableIM`, fixes https://github.com/withastro/astro/issues/5488.
I couldn't create a failing test, the bug only happens when the table is inside a slot so I tested it manually.
Bug fix.

fix: avoid nil pointer dereference in table parsing

---

.changeset/nine-ladybugs-exist.md
internal/parser.go
internal/transform/scope-html_test.go

- Removes `astro.ParseFragment` in favor of `astro.ParseFragmentWithOptions`
- Updates `astro.ParseFragmentWithOptions` to return an error when called w/o an error handler. Should it panic instead?
Might be worth adding a "expect error" test for `astro.ParseFragmentWithOptions` though idk where this function is tested, other than transitively via `scope_html_test.go`

Remove `astro.ParseFragment` / Require an error handler for `astro.ParseFragmentWithOptions`

---

.changeset/smooth-experts-reply.md
internal/loc/diagnostics.go
internal/token.go
packages/compiler/test/bad-styles/unclosed-style.ts

- Closes #647
- Replaces `fmt.Printf` statements in the tokenizer with proper warnings for unexpected characters. 
- Gracefully handles EOF now
Test added
Bug fix only

Replace internal logs with properly handled warnings

---

.changeset/sharp-tools-knock.md
internal/printer/printer.go
internal/printer/printer_test.go

- Passes the module's `moduleId` as the second argument to createComponent.
- This is used to enable head propagation. The Astro runtime creates a dependency map so that it can trace modules with head propagation to what pages they belong to, so that we wait for those components to run before sending out the head.
- This is an optional argument and is backwards compatible.
- Test added to confirm that the passed in moduleId is include as the second argument.
- Head propagation tests are in core.
N/A

Include the id in createComponent

---

.changeset/red-rules-smash.md
internal/token.go
internal/token_test.go
packages/compiler/test/basic/expressions.ts

- Closes #624
- Fixes `<` handling in expressions by peeking the next character to check for spaces and numbers. It's not a perfect check but it should work for 90% of cases.
Added tokenizer test to verify correct tokenization
Added WASM test to verify correct output
Bug fix only

Fix `<` edge case in expressions

---

.changeset/nine-ladybugs-exist.md
internal/transform/scope-html_test.go

Small bugfixes that will be eventually moved to other PRs
This PR is tracking the addition of a simple go based fuzzer to test the html parser / scoped styles generator.
I'll add fixes to bugs I discover as I go along, and then eventually I'll break out the bugs and this fuzzer into individually mergable PRs
This can be run via `go test ./internal/transform -fuzz=FuzzScopeHTML` from the root directory to run an ongoing fuzz test of the html scoping.
Uses https://tip.golang.org/doc/tutorial/fuzz
There should be contributor docs for how the fuzzer works, how to run it && how to update fuzz tests

Add a basic fuzzer - FuzzScopedHTML

---

.changeset/orange-bottles-bow.md
internal/parser.go
internal/printer/print-to-js.go
internal/transform/transform.go
packages/compiler/test/basic/script-before-html.ts

- Allows `script` nodes before the `html` node.
- Closes https://github.com/withastro/compiler/issues/660
- This was an edge case in our parser that was causing the actual `html` node to be ignored
Wasm test added
Bug fix only

Allow script/style before html

---

.changeset/quick-radios-cheer.md
internal/parser.go
packages/compiler/test/basic/body-after-head-component.ts

- Solve issue https://github.com/withastro/astro/issues/5557
- `Slot` in `head` tag will cause a situation that paser cannot exit from `inExpressionIM`
For file:
```js
---
const isProd = true;
---
<!DOCTYPE html>
<html lang="en">
<head>
<TestHead />
<title>document</title>
{isProd && <slot />}
</head>
<body style="color: red;">
<main>
<h1>Welcome to <span class="text-gradient">Astro</span></h1>
</main>
</body>
</html>
```
Before, compiler has the below output, it omits the `body` tag.
```js
const $$stdin = $$createComponent(async ($$result, $$props, $$slots) => {
const Astro = $$result.createAstro($$Astro, $$props, $$slots);
Astro.self = $$stdin;
const isProd = true;
return $$render`<html lang="en">
<head>
${$$renderComponent($$result,'TestHead',TestHead,{})}
<title>document</title> …
```

fix: corner case with slot expression in head will cause body tag missing

---

.changeset/ninety-emus-swim.md
internal/parser.go
packages/compiler/test/basic/body-after-head-component.ts

- The previous pr https://github.com/withastro/compiler/pull/671 has fixed the problem that `Slot` in `head` expression will cause `body` tag missing
- And I found that `Component` in `head` expression will cause the same problem. 
- Original Issue: https://github.com/withastro/astro/issues/5557 Minimal Reproducible Example: https://stackblitz.com/edit/github-uwb7te-xzq2mg?file=src%2Fcomponents%2FDocument.astro
- So, I think we should add `Component` Support in `inExpressionIM` function when it's in `head` tag.
Added
bug fix only

fix: corner case that component in head expression will case `body` tag missing

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snapshot-release.yml

- All jobs consistently complete in under 3min - this should bring the generous default down to something that we can detect. CI sorta PR!

chore: set github action timeout to 3min / job

---

.changeset/sixty-dragons-perform.md
.editorconfig
internal/printer/printer.go
internal/printer/printer_test.go

* Escape single quotes in module identifiers
* Added a test to the printer's tests
* no docs updated
---
its possible you can have a file named `foo'bar.astro` which currently will trip up the compiler, since it'd produce something along the lines of `createComponent(..., 'foo'bar')` (ofc syntactically incorrect).
let me know if this is the wrong way to fix it and i'll update
i also added an `editorconfig`, let me know if its wrong. it'd be useful to have one in this repo so contributors automatically use the right indentation etc

fix: handle module IDs containing quotes

---

.changeset/healthy-parents-smile.md
cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_css_test.go
internal/printer/printer_test.go
internal/transform/transform.go
packages/compiler/browser/utils.ts
packages/compiler/node/utils.ts
packages/compiler/shared/types.ts
packages/compiler/test/bad-styles/sass.ts
packages/compiler/test/basic/component-metadata/index.ts
packages/compiler/test/client-directive/special-characters.ts
packages/compiler/test/css-order/astro-styles.ts
packages/compiler/test/css-order/imported-styles.ts
packages/compiler/test/scope/same-source.ts
packages/compiler/test/static-extraction/css.ts
packages/compiler/test/static-extraction/hoist-expression.ts
packages/compiler/test/styles/define-vars.ts
packages/compiler/test/styles/sass.ts

- Closes #688 
- Removes `experimentalStaticExtraction` flag and related legacy code.
- Uses `experimentalStaticExtraction` behavior as the default.
Covered by existing tests, outdated tests updated
CHANGELOG updated

Baseline `experimentalStaticExtraction` flag

---

.changeset/spicy-ways-sing.md
cmd/astro-wasm/astro-wasm.go
internal/handler/handler.go
internal_wasm/utils/utils.go

- This adds some logic to intercept and format `panic`s so that we actually reject the `transform` promise with the correct error instead of just printing the error to stdout.
- ~~Trims irrelevant info from the stacktrace and formats to more helpful internal file location.~~
- ~~Formats errors similarly to JS stacktraces so that they don't confuse users~~
- Related to https://github.com/withastro/astro/pull/5855
Tested manually
| Before 	| After 	|
|:------:	|:-----:	|
| <img width="400" alt="old stacktrace" src="https://user-images.githubusercontent.com/7118177/212566271-007d1817-048a-4504-9d5d-7dcd41805de7.png"> | <img width="400" alt="new stacktrace" src="https://user-images.githubusercontent.com/7118177/212566263-dd1a7e99-b2c0-4943-92f2-acc94b996c7e.png"> |
N/A, QoL improvement

Improve error recovery

---

.changeset/big-papayas-breathe.md
internal/printer/printer_test.go
internal/transform/transform.go

- Hoisted scripts are removed and extracted to be inserted by Astro. 
- It should not cause a `maybeRenderHead()` as that will in some cases prematurely cause the head to be rendered out.
- It does *not* insert this for styles. hoisted scripts should behave the same.
- new test added
- updated tests which were falsely depending on the old behavior.
N/A, bug fix

Prevent inserting maybeRenderHead on hoisted scripts

---

.changeset/twenty-eels-notice.md
internal/transform/transform.go
packages/compiler/test/basic/trailing-spaces-ii.ts

- Fixes issue reported on Discord
- We would previously only collapse _one_ trailing text node
- Now we collapse _all_ trailing text nodes
Added fixture from reported repro

Collapse all trailing text nodes

---

.changeset/pink-maps-sip.md
cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
internal/transform/transform.go
packages/compiler/shared/types.ts
packages/compiler/test/slot-result/result.ts

- Adds the `resultScopedSlot` option. Using this option causes the slot to receive the `$$result` object. This is so that we can provide scoped result objects within the context of slots. This is used so that if head injection occurs we can conditionally on render head contents when we should; for example not to render head contents when a JSX component using an Astro component, but itself is used within a layout.
- Ideally we can remove this option in the future if we remove implicit head injection in a major version.
- Test for the option added
N/A

Pass through result to slot

---

.changeset/grumpy-eels-wave.md
packages/compiler/shared/types.ts

- Fixes incorrect `convertToTSX` types. 
- That function should accept `filename`, not the removed `sourcefile` option.
Tested manually, types only
Types only

Update tsx types

---

.changeset/tall-mails-impress.md
internal/printer/printer_test.go
internal/transform/transform.go

Fix https://github.com/withastro/compiler/issues/735
Makes a text node the value of `set:html` and `set:text` directives when using quoted or template literal attributes
Added tests to check if `set` directives using quoted or template literal attributes compile to text nodes
bug fix only

fix: quoted `set` directives to not inlined as text node

---

.changeset/weak-seals-serve.md
packages/compiler/browser/index.ts
packages/compiler/node/index.ts
packages/compiler/shared/types.ts
packages/compiler/test/teardown/parse.ts

Allow calling `teardown()` to free up memory. It's fine to continue calling `parse` or `transform` again, just that the previous cache would be gone.
It would be great to not need to call this, but the "caching" seems to be in the [Go class in wasm_exec.ts](https://github.com/withastro/compiler/blob/db033b6d88096abd439d2f8995323ad106255997/packages/compiler/node/wasm_exec.ts#L51), and they are cached in `_values` specifically, presumably at
https://github.com/withastro/compiler/blob/db033b6d88096abd439d2f8995323ad106255997/packages/compiler/node/wasm_exec.ts#L116
I'm not familiar with what it's doing so I figured to leave it be for now.
Added a simple teardown test, and make sure other APIs still work after tearing down.
n/a

Add teardown API

---

.changeset/tame-pillows-shake.md
internal/printer/printer_test.go
internal/transform/scope-html.go

Fix https://github.com/withastro/compiler/issues/737
Added test for when the `style` attribute is:
- A shorthand
- An expression
- Empty
- A template literal
- Quoted
We might need to document semicolon usage depending of the resolution taken in [this comment](https://github.com/withastro/compiler/pull/741#pullrequestreview-1318082743)

Fix `define:vars` when used with a `style` attribute

---

.changeset/tame-tables-taste.md
internal/parser.go
internal/printer/printer_test.go
internal/token_test.go

Fix https://github.com/withastro/compiler/issues/743
The form pointer element wasn't reset when going from `inExpressionIM` to `textIM` at the end of an expression inside a form element, which caused the following `form` elements to be ignored.
- Added a tokenizer test for a sanity check
- Added a printer test
bug fix only

Fix ignored `form` elements after a `form` element containing an expression

---

.changeset/yellow-cheetahs-drop.md
internal/printer/printer_test.go
internal/transform/transform.go

Closes https://github.com/withastro/compiler/issues/747
I applied a transformation where if we have `class` and `class:list`, we take value from `class` and merge it with `class:list`
So if we have something like this
```jsx
<p class="one" class:list={["two", "three"]}>
```
It will be result into something like this:
```jsx
<p class="one" class:list={["one", ["two", "three"]]}>
```
I checked we if we support arrays in an array inside `class:list`, and we do!
I added a test case to cover the transformation

fix: merge class and class:list values

---

internal/printer/printer_test.go
internal/token_test.go

https://github.com/withastro/compiler/pull/740 seems to have fixed https://github.com/withastro/compiler/issues/493.
This PR adds a test to close that issue.
No changeset needed.
Added a tokenizer and a printer test
Adds test only!

test(#493): add test fixture for self closing tags in switch statement scope

---

.changeset/flat-peaches-design.md
internal/js_scanner/js_scanner.go
internal/js_scanner/js_scanner_test.go
packages/compiler/test/basic/get-static-paths.ts

- Closes https://github.com/withastro/astro/issues/4929
- Fixes edge case with `getStaticPaths` export hoisting
Test added
Bug fix only

Fix export hoisting with inline TypeScript types

---

.changeset/purple-olives-punch.md
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

Add test for tokenizer evaluating nested expressions after self-closing tags.
See #755 for related bug.
Closes https://github.com/withastro/astro/issues/6589
`go test`
Just added test.

Add test for self-closing tags before expressions

---

.changeset/honest-hats-wash.md
cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/transform/transform.go
package.json
packages/compiler/shared/types.ts
packages/compiler/test/head-metadata/with-head.ts
packages/compiler/test/head-metadata/without-head.ts

- Adds metadata on whether the tree includes a head. This is used on the Astro side to know if the implicit head injection algorithm can be ignored. It should be in most cases.
- Added wasm tests
N/A, bug fix

Add metadata for head propagation

---

.changeset/smart-ties-punch.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Preserves whitespace in slots
- Takes care to only add whitespace when there are other elements, as the intended behavior is that a component with no children should not have whitespace added.
- This is part of (but does not fix) https://github.com/withastro/astro/issues/6561
- Had to update a bunch of them
N/A

Preserve whitespace in slots

---

.changeset/shiny-files-jam.md
package.json
packages/compiler/.gitignore
packages/compiler/node/index.ts
packages/compiler/node/sync.cts
packages/compiler/node/sync.ts
packages/compiler/package.json
packages/compiler/sync.d.ts
pnpm-lock.yaml

TypeScript unfortunately does not support running async methods inside its LanguageService API, so our language server needs a sync version of the compiler. Since WASM instantiation is async only, you still need at least one async init call, but then you can use all the methods sync. It's not perfect, but it at leasts allows us to not rely on `synckit`, which makes things slow
Why the separate file? `index.ts` has a call to `import.meta.url`, which prevented my CJS-based application to even import the file. Annoying. ESM in VS Code extensions when 😠
Tested manually
N/A

feat(sync): Add a sync and CJS entrypoint for editor tooling

---

packages/compiler/README.md

The link for CONTRIBUTING.md was using relative path and pointing to a non-existent file when opened inside packages/compiler.
n/a
link fix only

Fix CONTRIBUTING.md link in readme

---

.changeset/dry-knives-glow.md
packages/compiler/node/index.ts
packages/compiler/node/sync.cts

Whenever `transform` panic, the compiler force a restart of the service to avoid the "Go Program already Exited" error. This PR adds that mechanism to `parse` and `convertToTSX` as well. Otherwise it crashes our entire language-server whenever the compiler fails to convert a file to TSX
Tested manually, service isn't actually supposed to crash, ha!
N/A

Restart service on crashes when using `convertToTSX` and `parse` like for `transform`

---

.changeset/silly-countries-act.md
internal/printer/printer.go
packages/compiler/test/js-sourcemaps/windows-linereturns.ts

There's some specific cases where the length check wasn't enough and the compiler would crash. It was strangely hard to reproduce because in tests, the compiler would sometimes just hang and not fully crash and the test would be considered "pending" infinitely, super weird.
I'm also totally unsure why the current Windows tests don't catch this, very weird
Fix https://github.com/withastro/compiler/issues/786
Added a test
N/A

fix(windows): Fix crash when transforming files with Windows-style line endings

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snapshot-release.yml
CONTRIBUTING.md
package.json
pnpm-lock.yaml

- Update to pnpm 8
- Update test and release workflows to use node16 (required by pnpm8)
- We weren't testing node12 either even though we still support it, so I feel that this bump should be fine too
Existing test should pass.
Updated contributing docs with the newer pnpm version

Update to pnpm 8

---

.changeset/shaggy-jobs-deliver.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts
packages/compiler/test/tsx/non-latin.ts
packages/compiler/test/tsx/props-and-staticPaths.ts
packages/compiler/test/tsx/props.ts
packages/compiler/test/tsx/raw.ts
packages/compiler/test/tsx/script.ts

By not shifting the start of the file, it allows consumer downstream to always assume that the frontmatter is the beginning of the file, this is especially useful for mapping code actions and completions that are supposed to add code to the frontmatter since we can know where the frontmatter starts and end in the virtual file by using the positions of it in the real file
Ultimately, it'd be better to solve this in another way (maybe provide the location of the frontmatter in the virtual file), but this changes makes things easier in the meantime
Updated tests
N/A

fix: move declare const at the bottom of the file to make mapping easier downstream

---

.changeset/good-trains-matter.md
internal/transform/transform.go
internal/transform/transform_test.go
packages/compiler/test/compact/minify.ts

- Fixes https://github.com/withastro/astro/issues/7401
- We were preserving newlines, even if both _leading_ and _trailing_ newlines were present. Newlines should only be preserved if they are not symmetrical.
New test added
N/a, bug fix only

Fix `compressHTML` edge case

---

.changeset/soft-eggs-exercise.md
internal/transform/transform.go
internal/transform/transform_test.go
packages/compiler/test/compact/minify.ts

Closes #815. This issue came about as withastro/astro#7401 reported the previous whitespace-preserving behavior as incorrect, leading to #809. See [my comment](https://github.com/withastro/astro/issues/7401#issuecomment-1619327198) for why the behavior introduced by that PR is incorrect.
TLDR: revert #809 (& more)
I added a new test based on #815 and fixed a few problems with old tests.
Documentation not changed as this is purely a bugfix.

Preserve whitespace in text surrounded by newlines

---

.changeset/swift-crews-develop.md
internal/js_scanner/js_scanner.go
packages/compiler/test/tsx/props.ts

- Resolves https://github.com/withastro/compiler/issues/814
- Improves `Prop` import detection to avoid falsely detecting `import { Props as SomethingElse }` statements
Test added, this will also fix https://github.com/withastro/language-tools/issues/585 and remove the need for https://github.com/withastro/astro/pull/7550
No, bug fix only

fix(#814): improve Props import detection

---

.changeset/eight-ducks-invent.md
internal/parser.go
packages/compiler/test/parse/position.ts

- Resolves #802
- Includes end position in AST even when frontmatter is the only node in the file
Test added
Bug fix only

Capture closing frontmatter location on EOF

---

.changeset/orange-kangaroos-dress.md
internal/printer/print-to-json.go
internal/printer/printer_test.go
packages/compiler/src/browser/utils.ts
packages/compiler/src/node/utils.ts
packages/compiler/src/shared/ast.ts
packages/compiler/test/parse/serialize.ts

- Resolves #796
- In the AST, quoted attributes now contain their raw values
- This allows `serialize` to maintain the originally authored format of the attribute (double, single, or no quotes)
Test added
Need to update docs still!

Add raw attribute values to AST

---

.changeset/seven-moons-design.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx-sourcemaps/tags.ts
packages/compiler/test/tsx/basic.ts

- Resolves #801
- Maintains trailing whitespace in TSX output, which fixes TS completions in some cases
Two tests added

Maintain whitespace before tag close

---

.changeset/few-cats-happen.md
internal/printer/print-to-tsx.go

- Closes https://github.com/withastro/language-tools/issues/583
- Escapes more invalid characters in text nodes! Only thing not handled is if the initial character is `<` because that's probably an unclosed tag and we want to print it literally
Existing tests pass

[TSX] escape more invalid characters

---

.changeset/lazy-bats-play.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx-sourcemaps/attributes.ts

- Closes #825 
- Fixes mapping for quoted attributes with multiline values
Test added

[TSX] Fix multiline quoted attribute mapping

---

.changeset/young-turkeys-wave.md
cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go
packages/compiler/src/shared/types.ts
packages/compiler/test/basic/trailing-newline.ts

- `transition:animate` on an element is turned into `data-astro-transition-scope={renderTransition()}` which is used to create a scope name for the particular element and set up the CSS.
- Automatically includes the View transition CSS if one of the directives are used.
- Testing all done in core for now
N/A

Support for view transition directives

---

.changeset/silent-bags-lay.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Fixes this: `<div transition:name={post.data.slug}>`. Previously only worked correctly with string values.
- Test added
Bug fix

Handle expressions for transition:name

---

.github/workflows/congrats.yml

- Adds our Discord congrats bot to this repo
- Doesn’t do any filtering based on commit names (in other repos we ignore `[ci] format` but looks like that’s not a thing here)
- Uses a toolbox of emoji:
Same workflow we use in other repos.
N/A

Adds congrats workflow

---

.changeset/tall-keys-repair.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go

- Adds the `data-astro-transition-scope` var into components as well. This is needed so they can pass the result down to children, if they want.
- New test added
- N/A

Pass transition directives onto components

---

internal/printer/printer_test.go

re-enables printer tests (an `only: true` flag managed to slip in).
N/A
N/A

test: re-enable all printer tests

---

.changeset/itchy-lobsters-study.md
internal/printer/printer_css_test.go
internal/transform/scope-html.go
internal/transform/transform_test.go
lib/esbuild/css_printer/astro_features.go

Changes the generated attribute from `data-hash-astro-` to `data-hash-cid-`
Updated the test cases. They should all pass.

fix: change the name of the generated attribute

---

.changeset/popular-wombats-promise.md
cmd/astro-wasm/astro-wasm.go
internal/hash.go
internal/printer/printer_css_test.go
internal/printer/printer_test.go
internal/transform/scope-css_test.go
internal/transform/scope-html_test.go
internal/transform/transform_test.go
packages/compiler/test/basic/trailing-spaces-ii.ts

This PR changes the hash emitted by the compiler, by making it lower-case.
I updated all the test cases. The current CI should pass.
Internal change, is not needed

feat: lower case hash

---

.changeset/giant-boats-mate.md
cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go
internal/transform/transform_test.go
packages/compiler/src/shared/types.ts

- Removes `experimental` flags related to ViewTransitions (stable in 3.0)
- Will fix an error that throws in the current RC, since `astro` doesn't pass those flags anymore
Manually
N/A, bug fix

Remove experimental transition flags

---

.changeset/clean-sloths-try.md
cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/transform/transform.go
packages/compiler/src/shared/types.ts
packages/compiler/test/transition/meta.ts

- When `transition:` is used we are going to append styles. This adds the propagation flag to metadata so that Astro will propagate this up the tree, and wait for the component to load before resolving the head.
- Added JS test to see that it's part of the metadata.

Add propagation metadata to the TransformResult

---

.changeset/giant-chicken-arrive.md
internal/transform/scope-css_test.go
lib/esbuild/css_parser/css_parser.go
lib/esbuild/css_parser/css_parser_test.go
lib/esbuild/css_printer/css_printer_test.go

- Support CSS `@starting-style` rule (From: https://github.com/evanw/esbuild/pull/3249)
Add a new test cases
N/A

Support CSS `@starting-style` rule

---

.changeset/stupid-buttons-ring.md
internal/printer/printer.go
internal/printer/printer_test.go

- Closes #871 
- For reference: [runtime#spreadAttributes](https://github.com/withastro/astro/blob/astro@3.3.0/packages/astro/src/runtime/server/index.ts#L73)
- Added a printer snapshot test.
- Edited existing printer snapshot tests where name was expected.
Does not affect usage.

fix(improper escaping): do not print "name"

---

.changeset/large-geese-kick.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/props-and-getStaticPaths.ts

- Automatically inferred `Props` has shipped!
- There was an edge case with union `Props` where they couldn't be destructured. 
- This PR adds a `MergeUnion` utility to flatten unions into each other so that divergent props don't need to be manually discriminated before destructuring.
Test updated, type util manually tested
Bug fix only

fix(tsx): add `MergeUnion` util to automatically inferred Props

---

.changeset/stale-steaks-brush.md
cmd/astro-wasm/astro-wasm.go
internal/printer/print-to-js.go
internal/transform/scope-html.go
internal/transform/transform.go
internal/transform/transform_test.go
packages/compiler/src/shared/types.ts

- Allows Astro compiler to annotate elements with information about their source file and location
- Planned for improving DX in Astro core during dev
- Tests added
N/A

Add `annotateSourceFile` option

---

.changeset/real-mice-exist.md
internal/transform/transform.go
internal/transform/transform_test.go
packages/compiler/test/compact/minify.ts

fix https://github.com/withastro/compiler/issues/879
We're previously collapsing empty text nodes (only contains whitespace) to `""`, but sometimes this is unsafe and should convey a `" "` instead (one space).
This PR checks for cases where we can collapse completely with no spaces, but otherwise would only always collapse to one space. I'm not sure if there's a safer way else to deal with it.
Added new test in go
n/a. bug fix.

Fix compact for empty text nodes in elements

---

.changeset/odd-dryers-flow.md
internal/parser.go
internal/printer/printer_test.go

Fix https://github.com/withastro/compiler/issues/870
For starting expressions within a table cell (`td`), `p.exitLiteralIM` (used to check when we can exit the insertion mode while parsing literals) was not assigned so the exit check at
https://github.com/withastro/compiler/blob/f5cff0127d2b2ea59201f6f84d308c57540bde68/internal/parser.go#L2697
Always returned false (default behaviour). Causing any tokens after the first `{` expression to be considered a literal incorrectly, since it'll never exit the insertion mode.
This PR sets `p.exitLiteralIM` to fix it, and also fix a slightly unrelated issue where exiting the literal IM in a table returned to a body IM, which I think is incorrect (?).
Added a new test in go
n/a. bug fix

Fix expressions within td exitLiteralIM tracking

---

.changeset/stupid-rats-cough.md
internal/parser.go
internal/printer/printer_test.go

- This reverts commit e241f2d545e5753eaafe19fac8626f0191cca96c.
- Don't want to break people, going to release this quickly. Can circle back to actually fix the table issue.
The following case regressed, throwing a parsing error for the user. Notably, even with the regression, this case is still broken, albeit not fatally. Tables are fun! 😭
```astro
---
const content = "lol";
---
<html>
<body>
<table>
<tr>
<td>{content}</td>
</tr>
{
(
<tr>
<td>1</td>
</tr>
)
}
</table>
1
</body>
</html>
```
N/A

Revert "Fix expressions within td exitLiteralIM tracking (#885)"

---

.changeset/late-readers-reflect.md
internal/parser.go
internal/transform/transform_test.go

Fix #880
We were trying to access an element of a slice (stack of open elements) without making sure it exists.
Added a transform test
N/A Bug fix

fix: `index out of range [0]` error when compent is before the html tag

---

.changeset/strange-beans-scream.md
internal/printer/printer.go
internal/printer/printer_test.go
packages/compiler/test/tsx/line-terminator.ts

Fix #872
The initial code inaccurately incremented `start` for each character iteration without considering variable byte sizes. The updated code utilizing `utf8.DecodeRuneInString`, correctly adjusts `start` based on the byte size of each character.
N/A bug fix

fix: better sourcemaps handling with multibyte characters

---

.changeset/dull-bees-grab.md
.vscode/settings.json
internal/printer/printer_test.go
internal/sourcemap/sourcemap.go
packages/compiler/test/tsx-sourcemaps/multibyte.ts

- Closes https://github.com/withastro/astro/issues/9421
- Closes https://github.com/withastro/compiler/issues/733
- When generating sourcemaps, we were unconditionally accessing an index. For multi-byte characters, this index was sometimes out of range.
- This PR adds a `len()` check before access the index, which guards against the issue.
- There might be a more fundamental fix here, but I really don't think it's a great idea to dig into the sourcemapping logic to try to find it.
Tests added for cases that have been reported to throw
Bug fix only

Fix multibyte character handling

---

.changeset/big-crabs-burn.md
internal/parser.go
internal/printer/printer_test.go

- Fixes a crash discovered in https://github.com/withastro/astro/pull/9445
- When an expression is the final node in a file, we need to check the access to `p.oe.top()` to ensure there is actually an open element.
Test added
Bug fix only

Fix expression parsing when final node

---

.changeset/perfect-falcons-build.md
internal/printer/printer.go
internal/printer/printer_test.go

Fix #903
Components with template literal attributes were printed with the attribute name as value.
N/A bug fix

Fix template literal attributes on components

---

.changeset/kind-buses-punch.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx-sourcemaps/tags.ts
packages/compiler/test/tsx/basic.ts
packages/compiler/test/tsx/non-latin.ts
packages/compiler/test/tsx/props-and-getStaticPaths.ts
packages/compiler/test/tsx/props.ts
packages/compiler/test/tsx/raw.ts
packages/compiler/test/tsx/script.ts
packages/compiler/test/utils.ts

Add `/** @jsxImportSource astro */` to our TSX output so it uses the newly exported types at https://github.com/withastro/astro/pull/9501, this is all to attempt to fix https://github.com/withastro/language-tools/issues/727
Adjusted tests
N/A

feat(tsx): Prefix tsx output with a JSX pragma

---

.changeset/smooth-timers-remember.md
internal/printer/print-to-tsx.go
internal/printer/utils.go
packages/compiler/test/tsx/escape.ts

- Closes #922
- Always insert a space after opening comments
- Escape `*/`  into `*\/`
Added TS tests:
- For escaping curly braces, didn't find any that covered that.
- For escaping `*/`
- To make sure a space is always inserted after an opening comment in the tsx output
N/A bug fix only

fix(tsx): prevent slashes in html comment from causing premature closing of comments in the tsx output

---

.changeset/fair-windows-wave.md
cmd/astro-wasm/astro-wasm.go
internal/loc/loc.go
internal/printer/print-to-tsx.go
internal/printer/printer.go
packages/compiler/src/shared/types.ts
packages/compiler/test/tsx/basic.ts
packages/compiler/test/tsx/escape.ts

A common issue in the language server is it being hard to map things to the "frontmatter" of the TSX file because, well, we don't know where it is inside the TSX. This PR now returns the start and end of both the frontmatter and the body of the file, which the language server can use to map things.
This is for https://github.com/withastro/language-tools/pull/733
Added a test
N/A, I updated the types though

feat(tsx): Return interesting ranges for TSX output

---

.changeset/poor-cheetahs-talk.md
internal/parser.go
internal/printer/print-to-js.go
internal/printer/print-to-tsx.go
internal/printer/printer_test.go
packages/compiler/test/basic/expression-then-node.ts
packages/compiler/test/tsx/comment-whitespace.ts

- Fix https://github.com/withastro/compiler/issues/784
- The parser doesn't remove whitespace in expressions anymore
- Don't remove expressions that only contain comments in the TSX output
- Handle empty expressions containing only whitespace as before (see https://github.com/withastro/compiler/pull/930/files#r1437911849)
- Adjusted whitespace in a few tests
- Added a printer test to make sure empty expressions that contain whitespace are handled like before.
- Added a TSX output test to ensure the whitespace in expressions is respected
N/A bug fix

Don't ignore whitespace in expressions

---

.changeset/perfect-fishes-cover.md
internal/parser.go
internal/printer/printer_test.go

- Fixes #870
- Fixes #695
Inside a `table` element, when there was an implied `tr` tag which had a `td` or `th` which contained an expression (that's a mouthful yeah 😅), it would cause any trailing element/component/text node to be swallowed by the table element (just before the `table` closing tag). This fixes that.
- Edit the (deliberately) incorrect printer test case introduced in #889
- Brought back the test case reverted in that PR to makes sure that trailing elements aren't swallowed
N/A bug fix

Fix incorrect table parsing when it contains expressions in certain cases

---

.changeset/hot-clocks-judge.md
internal/printer/print-to-js.go
internal/printer/printer_test.go
packages/compiler/test/tsx/comment-whitespace.ts

https://github.com/withastro/compiler/pull/930 introduced a regression which broke a test added in https://github.com/withastro/compiler/pull/928, but we didn't catch that probably because we didn't update the branch before merging. This fixes the regression and updates tests
Update tests to account for recently merged changes
N/A bug fix

Prevent printing tagged render function on whitespace only text nodes

---

.changeset/chilled-starfishes-search.md
internal/printer/print-to-json.go
internal/printer/printer_test.go
internal/token.go
packages/compiler/test/tsx-sourcemaps/unfinished-literal.ts

- Fix #904
- Complement to #636.
Fix an issue where unterminated quoted attributes caused the compiler to crash
Added a TSX output test to make sure the compiler doesn't crash
N/A bug fix

fix(tokenizer): handle unterminated quoted attributes gracefully

---

.changeset/plenty-mice-beam.md
internal/parser.go
internal/printer/printer_test.go

- Closes #722
- Ensure parsing of fragments in table elements
N/A bug fix

Fix fragment in `tr` printing incorrect output

---

.changeset/strong-chairs-walk.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

Found the issue on [discord](https://discord.com/channels/830184174198718474/830184175176122389/1194085209369477130)
Fixes a regression introduced in https://github.com/withastro/compiler/pull/930. We were only looking for `nil` or an empty text node in the first child of the expression, instead making sure that all children match that criteria before assuming it's an empty expression
N/A bug fix

Fix regression in expressions

---

.changeset/kind-cheetahs-listen.md
internal/sourcemap/sourcemap.go
packages/compiler/test/parse/multibyte-characters.ts

- Fixes #936
- `GetLineAndColumnForLocation` is used for generating sourcemaps for JS and TSX and locations in the AST
- The function was not safely handling indexed access, meaning that multibyte characters could crash the program
New test added!

Safer handling for `GetLineAndColumnForLocation`

---

.changeset/fuzzy-bulldogs-add.md
internal/js_scanner/js_scanner.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go

- Closes https://github.com/withastro/compiler/issues/899
- Generate a correct `exportName` for namespaced default exports
- Remove duplicated code that determines the exported module's object path
- Added tests for namespaced components imported from default and named exports
- I'll add a test in core too after we get this merged
N/A bug fix only

Fix wrong component object path for namespaced default exported components

---

.changeset/dull-socks-provide.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Closes #950
- More granular printing of `mergeSlots`
A regression in how we print slot was introduced in my PR in https://github.com/withastro/compiler/pull/933.
Normally, if there is more than one slotted element or any slotted element with dynamic `slot` prop in an expression, we consider it a nested slot. However, instead of doing the count per expression, we aggregated it for all expressions.
Because of that, if there were any slotted element in an expression, any subsequent slotted element of the same kind would be considered a nested slot
To fix that, we localized each of those states per expression
- Adapted and added a few printer tests to reflect the changes and ensure a correct output
- Added tests to Astro core to ensure a correct result
N/A bug fix only

Fix slot regression when there are multiple expressions

---

.changeset/young-cougars-enjoy.md
internal/parser.go
internal/printer/printer_test.go

Fix [an issue reported on discord](https://discord.com/channels/830184174198718474/1199343177446998116/1199343177446998116) in which if there were an expression in a `th` element, that would cause an infinite loop
This regression was introduced in 2.4.0, but I'm not sure what exactly caused it
Added printer test to make sure that it doesn't hang and it's printed correctly
N/A bug fix only

Fix expression in `th` causing infinite loop

---

.changeset/gold-bananas-drum.md
internal/printer/print-to-js.go
internal/printer/printer_test.go

- Revert #933
- Revert #952
- Close https://github.com/withastro/compiler/issues/959
- Close https://github.com/withastro/compiler/issues/955
- Reopen https://github.com/withastro/compiler/issues/868
- Reopen https://github.com/withastro/compiler/issues/724
#933 ended up causing too many severe regressions so we decided to roll it back until we can do get extensive testing done for the dynamic slot feature. 
- Reverted all tests from these two PRs
- Removed the tests added in core for this feature (TODO)
- Added tests to close the issues
Remove the references of this feature in docs (TODO)

Revert "Fix slot regression when there are multiple expressions (#952)"

---

.changeset/bright-lemons-fry.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts
packages/compiler/test/utils.ts

I'm not sure why I thought it had to be a `/**` comment, it's not necessary. This was causing the first const in a component to be marked by the JSDoc.
Tests should pass! [I also tested that this works in the TypeScript playground](https://www.typescriptlang.org/play?#code/PQKgBAAgVgzgHgSQLYAcD2AnALgZTQVwwGMBTMDEgQyKzBGACgGS51swAzfAOxoEs03MAGE0qQSW5YAFAEowAbwZhyJLISEAeACZ8AbmGAA+BgF8GQA)
N/A

fix(tsx): Remove unnecessary jsdoc comment

---

.changeset/gold-apples-shout.md
cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/parser.go
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go
packages/compiler/src/shared/types.ts

This PR allows rendering non-inline script tags using a runtime API from `internalURL`, e.g.
```html
<script>console.log("a")</script>
```
becomes:
```js
`${$$renderScript($$metadata, "/src/pages/index.astro?astro&type=script&index=0&lang.ts")}`
```
Personally I'm not a fan of the hardcoded script URL default, but the styles were also hardcoded this way, and it was easier to implement.
Added go tests
Only added jsdoc to the types explaining this feature. Options added in the past didn't have public docs either (?)

Add renderScript option

---

.changeset/cuddly-pumas-call.md
internal/handler/handler.go
internal/transform/transform.go
packages/compiler/test/client-directive/warn.ts
packages/compiler/test/scripts/isinline-hint.ts

- https://github.com/withastro/roadmap/blob/main/proposals/0016-style-script-defaults.md?plain=1#L74
Added `scripts/isinline-hint.ts`.
Would like docs review on the message.

Add lint rule for implicit `is:inline` on script tags.

---

.changeset/modern-flies-watch.md
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snapshot-release.yml

The plan is to update all action that log deprecation warnings starting with pnpm/action-setup.
I will keep this PR open as long as I try to cover the most common workflows.
- Updated actions/setup-go@v2 to v5
- Updated actions/checkout@v2/v3 to V4
- Updated pnpm/action-setup@v2 to v3
- Update actions/setup-node@v2 to v4
- Update golangci/golangci-lint-action@v2 to v4
- Update actions/github-script@v6 to v7
> - No new version for lannonbr/repo-permission-check-action@2.0.0
> - No new version for eficode/resolve-pr-refs@main
Not addressed in this PR:
- The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 
scan github …

Updates deprecated Node.js 16 github actions

---

.changeset/real-otters-mix.md
internal/printer/printer.go
internal/printer/printer_test.go
internal/transform/transform.go

- Implements `transition:persist-props` as explained in https://github.com/withastro/astro/pull/10136
- This is a simple transformation to `data-astro-transition-persist-props` with the same value.
- Very similar to how `transition:persist` works.
- This means for dynamic use-cases users can use the `data-` attribute instead.
- New test case added
- https://github.com/withastro/docs/pull/6915

Implement transition:persist-props

---

.github/workflows/snapshot-release.yml

Drop `lannonbr/repo-permission-check-action` for [`actions-cool/check-user-permission`](https://github.com/actions-cool/maintain-one-comment)
The earlier wasn't working anymore [after we updated it](https://github.com/withastro/compiler/pull/972/files#diff-9dc5e53b8fc4bd9d74ca8c2d8d9d5bf7f94c6a8ccc49f2bcc142ec5c171686d1R19).
[Martin opened an issue](https://github.com/actions-cool/maintain-one-comment) on that repo to suggest updating to Node 20 (to remove the deprecation warnings) but I'm not sure it's gonna move forward as the repo looks abandoned.
I checked, and the main repo doesn't currently use the bugged version of the action, but to get rid of the warnings, we shall make the switch to the better maintained one.
Not tested but the usage looked straightforward after looking at the …

chore: use better maintained permission checker action 

---

.github/workflows/snapshot-release.yml

The snapshot workflow in https://github.com/withastro/compiler/pull/977 returned `0` instead of `1`, causing the workflow to not fail for non-admins.
Not tested but the only issue was the wrong exit code which wouldn't stop the workflow
N/A doesn't affect users

chore: fix exit code for failed permission check

---

.github/workflows/snapshot-release.yml

- Snapshot releases weren't building wasm. They should

Make snapshot releases build the wasm

---

.changeset/khaki-schools-reflect.md
internal/parser.go
internal/printer/printer_test.go

- Since `resetInsertionMode` is used when expressions are ended there needs to be something on the `templateStack` for nested expressions. 
- There should be an `inExpressionIM` in the `templateStack`.
- Fixes https://github.com/withastro/compiler/issues/985
- Fixes https://github.com/withastro/compiler/issues/935
- New printer test
N/A, bug fix

Fix issue with head content pushed into body

---

.changeset/tender-rockets-agree.md
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/snapshot-release.yml
CONTRIBUTING.md
go.mod
packages/compiler/src/browser/wasm_exec.ts
packages/compiler/src/node/wasm_exec.ts

- Updates the entrypoint to reflect renaming of the imports object in 1.20.
- Existing tests should pass.
- Does not affect usage.

chore: upgrade to go 1.22

---

.changeset/khaki-ways-wait.md
internal/printer/print-to-js.go
internal/printer/printer.go
internal/printer/printer_test.go

Idea from https://github.com/withastro/astro/pull/10773#pullrequestreview-2005386326
If the `Astro` global is not used, we don't need to print code that calls `createAstro`. This saves on runtime execution as it's created but not used.
---
Perf:
- `createAstro()` calls dropped from 571ms o 551ms. -0.02s (not a lot, but it helps other cases instead like garbage collection and AST parsing)
- `garbage collection` dropped from  59.52s to 40.88s. -18.7s
Updated tests to handle cases where the `createAstro` code is no longer present.
n/a. internal improvement.

Skip printing `createAstro` code if unused

---

.changeset/warm-zebras-rest.md
internal/printer/printer.go
internal/printer/printer_test.go

Idea by @natemoo-re. Currently we always print the component function with async even if no top-level await is used:
```js
const $$stdin = $$createComponent(async ($$result, $$props, $$slots) => {
```
We can skip printing the `async` if no `await` is used so that rendering the component won't always require one tick.
---
Performance:
This should improve page rendering. With the Astro docs repo, it fluctuates between 35-42s a lot, so it's hard to make a concrete comparison. But compared to the old timings, the average timing dropped about 1-2s.
Updated test
n/a. internal improvement.

Skip printing async if await is not used

---

.changeset/light-ligers-rhyme.md
internal/transform/transform.go
packages/compiler/test/transition/data-astro.ts

- Removes the diagnostic disallowing `data-astro-reload` from having a value.
- I don't know the context for why this was added, but it prevents people from making the property from being conditional, ala `data-astro-reload={false}`. As far as I know we don't care about the value on the front-end.
- https://github.com/withastro/compiler/issues/1006
- Updated the existing tests around this
N/A, bug fix

Allow data-astro-reload to take a value

---

.changeset/red-crabs-cough.md
internal/transform/scope-html.go
internal/transform/scope-html_test.go

- Closes #1005
- Updates scoped class expression attributes to use nullish coalescing and avoid stringifying `undefined` as recommended by @bluwy.
- Updates tests for the new expected syntax
n/a — bug fix

Avoid stringifying `undefined` in scoped class attributes

---

.changeset/nine-ants-bow.md
.changeset/yellow-cooks-deliver.md
cmd/astro-wasm/astro-wasm.go
internal/node.go
internal/transform/transform.go
packages/compiler/src/shared/types.ts
packages/compiler/test/server-islands/meta.ts

- Discovers `server:defer` directive usage, then links that back to the import statement like what is done with `client:` islands. This information is exported as part of the compile result, on the `serverComponents` field, to be used by Astro.
- Since the only visible change is to the metadata, this is tested by adding a wasm test, to verify that the information is included and is correct.
N/A

Add server island metadata

---

.changeset/tame-games-fold.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/script.ts

Script tags with unknown content were not properly escaped / excluded (depending on the includeScripts setting), this fixes that
Added more tests for this edge case
N/A

fix: escape / exclude scripts with unknown types

---

.changeset/bright-plums-suffer.md
internal/js_scanner/js_scanner.go
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/top-level-returns.ts

This PR makes it so top level returns are transformed into throws in the generated TSX
Fixes https://github.com/withastro/language-tools/issues/476
Added a test
N/A

fix(tsx): Transform top level returns into throws

---

.github/workflows/issue-needs-repro.yml

When this was setup on the main repo, this repo didn't get the workflow
N/A
N/A

ci: add workflow to close issues without repro automatically

---

.changeset/angry-donuts-punch.md
internal/printer/print-to-tsx.go
internal/printer/printer.go
packages/compiler/src/shared/types.ts
packages/compiler/test/tsx/meta.ts

A long time ago, our language tooling would provide helpful intellisense inside SCSS and LESS tags, this was lost without notice. A recent regression made me remember this, so this PR brings it back
Additionally, this PR changes the script tag extraction a bit to handle `is:raw` and other edge cases better.
Added tests
N/A

Adds detected language to extracted style tags in TSX

---

.changeset/two-ghosts-fly.md
internal/printer/print-to-tsx.go
internal/printer/printer.go
packages/compiler/test/tsx/meta.ts

When I added the ability to skip script and styles, I forgot to take into account that we should still collect the multibytes characters inside of them as we use it to adjust the positions of tags
Additionally, this PR fixes the order in which the end positions are collected, previously we'd collect it before it got adjusted after printing, which lead to the end positions being wrong most of the time. This didn't end up being a problem in the editor tooling, as we don't care too much about end positions (we map from the start position)
Added a test and updated the tests for the end positions fixes
N/A

fix(tsx): Collect multibytes characters in skipped script and styles

---

.changeset/selfish-dogs-love.md
internal/printer/print-to-tsx.go
internal/printer/print-to-tsx_test.go
internal/printer/printer.go
internal/sourcemap/sourcemap.go
packages/compiler/src/shared/types.ts
packages/compiler/test/tsx/meta.ts

Previously when extracting script and style tags, we tried to somewhat make it work with multibytes characters by counting them and skipping, not only was this cumbersome, it kinda didn't work because our loop would run multiple times over kinda the same characters, anyway it was annoying.
In this PR, I changed it so that we use the lineoffsets table from the sourcemapping logic to get the offsets. This is somewhat slower, especially in some extreme cases, but in most cases there's no difference, and at least it's now correct.
I also updated the frontmatter and body ranges extraction to use this method, as they suffered from the same problem
In theory, this is a breaking change, but the truth is that the numbers it'd spit out would be unusable in JS unless you did a lot of conversion …

fix(tsx): Extract positions based on utf-16 encoding

---

.changeset/ten-melons-return.md
internal/transform/transform.go
internal/transform/transform_test.go

Resolved an issue where the class:list directive was not properly merging with the class attribute.
Fixes [withastro/compiler/issues/998](https://github.com/withastro/compiler/issues/998)
Added new tests to verify the correct merging of class and class:list attributes.
Manually tested the output to confirm that classes are accurately combined.
No documentation updates were made, as this change addresses an existing bug and does not introduce new features or alter existing functionality.

fix/class:list directive was not properly merging with the class attribute

---

.changeset/eleven-planets-camp.md
internal/printer/printer.go
packages/compiler/test/tsx-sourcemaps/template-windows.ts

Previously, due to how we skipped over CRLF, we'd end up with a mapping that looks like this:
```
Original:  ;    \n
Mapping : [;\r][\n]
```
Where the first segment would contain both the last character of the line, and the `\r`. This is fine, albeit wonky, however this ends up breaking downstream in libraries that are line-ending agnostic because they don't expect than an offset would end up after a line ending, even less so in the middle of a two-characters one. (the main culprit here is https://github.com/microsoft/vscode-languageserver-node/tree/main/textDocument, see https://github.com/microsoft/vscode-languageserver-node/issues/1285)
This PR fixes this by handling it like this instead:
```
Original:  ;  \n
Mapping : [;][\r\n]
```
That way, asking for the last segment of a line will …

Fix line returns segments being one character too long on Windows

---

.changeset/tiny-buses-hide.md
internal/printer/print-to-tsx.go
packages/compiler/test/tsx/basic.ts

- closes #1053
- issue was caused by a line break token immediately before the fragment ([repro](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMTU2LDgwLDE2MiwxMDMsMiwzLDEwMSwxNDUsNzcsNzksMTk1LDQ4LDEyLDEzNCwyNTUsNzQsMjAxLDEzMywyMDMsNTgsMTkwLDExMCwyMTEsNTIsMTA1LDIyNiw3NSw3MiwyOCwyMDgsOTAsOTYsNyw0Niw4OSwyMjYsNjUsNjgsMjM0LDY4LDE0MiwyMDMsMTI4LDEwNSwyNTUsMjksMTgzLDI5LDEwOCwxNzIsMTgzLDIxNiwyMzksMTU1LDIzMSwxODEsMTQ3LDE4MSw1MCw1MywxNywzMiw5NSwxMzQsNDIsNTgsMTUsMjQ0LDQsMTQ4LDkyLDY0LDUzLDgyLDIzMSwxOTUsMTc5LDIxMSwyMjUsMTMzLDI2LDQwLDE5LDQ0LDcyLDYxLDE1OCw3NiwyNDEsNDMsMTA3LDEzOCw1Miw2MiwxNTMsMTQwLDM5LDIyOSwxNTUsNzUsMjE3LDQyLDIwOCwxMjMsODMsMTkwLDIyNCwxODIsOTcsMywzNiw2MCwyMzAsODYsMTA0LDI1MSwxNjIsMjgsMjI5LDEyMSwxMTgsMjUzLDI1LDksODIsMTMxLDIwNiwyNDIsOTIsMjE4LDIzNSwzLDE5Miw3MCwxMzAsMjI4LD …

Fix extra space in fragment

---

.changeset/plenty-geese-laugh.md
internal/parser.go
internal/printer/__printer_js__/namespace_is_preserved_when_inside_an_expression.snap
internal/printer/printer_test.go

- closes https://github.com/withastro/compiler/issues/1063
This PR adds the current `Namespace` to the expression Node.
When writing an expression inside foreign content (i.e. SVG) the astro compiler did not persist the namespace and therefore parsed the contained nodes in normal HTML mode. This lead to `<image>` tags incorrectly being transformed to `<img>` tags, but could also have caused other Problems.
- added printer test to validate correct parsing of `{<image />}` inside svg
bug fix only

Fix expression parsing in foreign context

---

.changeset/olive-beds-happen.md
cmd/astro-wasm/astro-wasm.go
internal/printer/__printer_js__/multiple_define_vars_on_style.snap
internal/printer/__printer_js__/script_multiple__renderScript__true_.snap
internal/printer/printer_css_test.go
internal/printer/printer_test.go
internal/transform/transform.go
internal/transform/transform_test.go
packages/compiler/src/shared/types.ts
packages/compiler/test/scripts/order.ts
packages/compiler/test/styles/sass.ts

- Fixes https://github.com/withastro/astro/issues/12264 (See https://github.com/withastro/astro/issues/12264#issuecomment-2544037010 for more info)
For example, with component like the follow:
```html
<style>
body {
background-color: red;
}
</style>
<style>
body {
background-color: yellow;
}
</style>
```
The current compiler output would render `red` last, even though `yellow` was the last style-tag defined.
```html
<style>
body {
background-color: yellow;
}
body {
background-color: red;
}
</style>
```
Enabling the `experimentalScriptOrder` flag will respect the order style & script tags are defined.
```html
<style>
body {
background-color: red;
}
body {
background-color: yellow;
}
</style>
```
- Updated existing styles test
- Added test for scripts order
- Will require a section for the …

Reverse order of styles & scripts

---

.changeset/soft-adults-switch.md
internal/transform/transform.go
packages/compiler/test/server-islands/meta.ts

This PR adds head propagation for server island directives.
We need head propagation because the server islands generate some script during the rendering phase, and if we want to support CSP, we need to hash the rendered script and then render the meta tag inside the `head` element.
This is exactly the same thing that we already do with view transitions.
Added a new test

feat: head propagation for server islands

---

.changeset/tough-months-melt.md
packages/compiler/README.md
packages/compiler/src/browser/utils.ts
packages/compiler/src/node/utils.ts

- Adds `walkAsync`, which returns the already-async `Walker.visit`
- Inspired by https://github.com/MoustaphaDev/astro-default-prerender/blob/139e1574f621029293a53db8d8e3999be170be70/packages/integration/src/index.ts#L129-L131
I did not see any tests for the base `walk` utilility.
Yes, minor tweaks to the utils section of the Readme, with an example of when this would be useful.

Introduce asynchronous walk function

---

cmd/astro-wasm/astro-wasm.go
go.mod
internal_wasm/utils/utils.go

Mark files that rely on `syscall/js` with build tags targeting JS and WASM, the same as the `syscall/js` package itself.
GoPls shows this warning when working on the project locally so things get annoying with tools that aim to keep the project always green like preventing commits in a broken state without extra confirmation jumping to definitions to explore the codebase since it consider those references broken.
Which then makes GoPls consider all the imports that are JS-only as exporting nothing:
Additionally, `go.mod` had a dependency marked as indirect but it is actually used directly by our tests. So just running `go mod tidy` causes the changes committed there.

Fix LSP warnings and navigation on JS-related code

---

.changeset/happy-ways-collect.md
internal/parser.go
internal/printer/__printer_js__/selectedcontent_element_in_customizable_select.snap
internal/printer/__printer_js__/selectedcontent_self-closing_element.snap
internal/printer/print-to-js.go
internal/printer/printer_test.go
internal/token.go
internal/token_test.go

Closes #1093
The `<selectedcontent>` element is used inside customizable `<select>` elements to display the currently selected option within a custom button. It's part of the new web standard for styleable select elements that's been years in the making.
```html
<select>
<button>
<selectedcontent></selectedcontent>
</button>
<option>Option 1</option>
<option>Option 2</option>
</select>
```
Without this fix, the Astro compiler treats <selectedcontent> as a regular container element, causing it to incorrectly consume all following elements until the parent's closing tag. This breaks the structure of customizable select elements.
Before: Options incorrectly nested inside selectedcontent
```
<selectedcontent>
<option>Option 1</option>
<option>Option 2</option>
</button>
```
After: Correct …

Fix: Support HTML `<selectedcontent>` element

---

.changeset/silver-deers-buy.md
cmd/astro-wasm/astro-wasm.go
internal/printer/printer_css_test.go
internal/printer/printer_test.go
internal/transform/transform.go
packages/compiler/src/shared/types.ts
packages/compiler/test/scripts/order.ts
packages/compiler/test/styles/sass.ts

- It is now the default
Should pass
Changeset

feat: remove experimentalScriptOrder option
